// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         int32                  `protobuf:"varint,2,opt,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserTokenRequest) Reset() {
	*x = CreateUserTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserTokenRequest) ProtoMessage() {}

func (x *CreateUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserTokenRequest) GetRoles() int32 {
	if x != nil {
		return x.Roles
	}
	return 0
}

type CreateUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserTokenResponse) Reset() {
	*x = CreateUserTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserTokenResponse) ProtoMessage() {}

func (x *CreateUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateUserTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type CreateDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceTokenRequest) Reset() {
	*x = CreateDeviceTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceTokenRequest) ProtoMessage() {}

func (x *CreateDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeviceTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateDeviceTokenRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type CreateDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceTokenResponse) Reset() {
	*x = CreateDeviceTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceTokenResponse) ProtoMessage() {}

func (x *CreateDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDeviceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateServiceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceTokenRequest) Reset() {
	*x = CreateServiceTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTokenRequest) ProtoMessage() {}

func (x *CreateServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateServiceTokenRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type CreateServiceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceTokenResponse) Reset() {
	*x = CreateServiceTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTokenResponse) ProtoMessage() {}

func (x *CreateServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CreateServiceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseUserTokenRequest) Reset() {
	*x = ParseUserTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseUserTokenRequest) ProtoMessage() {}

func (x *ParseUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseUserTokenRequest.ProtoReflect.Descriptor instead.
func (*ParseUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ParseUserTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ParseUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         int32                  `protobuf:"varint,2,opt,name=roles,proto3" json:"roles,omitempty"`
	TokenId       string                 `protobuf:"bytes,3,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ExpriresAt    int64                  `protobuf:"varint,4,opt,name=exprires_at,json=expriresAt,proto3" json:"exprires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseUserTokenResponse) Reset() {
	*x = ParseUserTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseUserTokenResponse) ProtoMessage() {}

func (x *ParseUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseUserTokenResponse.ProtoReflect.Descriptor instead.
func (*ParseUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ParseUserTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParseUserTokenResponse) GetRoles() int32 {
	if x != nil {
		return x.Roles
	}
	return 0
}

func (x *ParseUserTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ParseUserTokenResponse) GetExpriresAt() int64 {
	if x != nil {
		return x.ExpriresAt
	}
	return 0
}

type ParseServiceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseServiceTokenRequest) Reset() {
	*x = ParseServiceTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseServiceTokenRequest) ProtoMessage() {}

func (x *ParseServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*ParseServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ParseServiceTokenRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ParseServiceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseServiceTokenResponse) Reset() {
	*x = ParseServiceTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseServiceTokenResponse) ProtoMessage() {}

func (x *ParseServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*ParseServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ParseServiceTokenResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type ParseDeviceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDeviceTokenRequest) Reset() {
	*x = ParseDeviceTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDeviceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDeviceTokenRequest) ProtoMessage() {}

func (x *ParseDeviceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDeviceTokenRequest.ProtoReflect.Descriptor instead.
func (*ParseDeviceTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ParseDeviceTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ParseDeviceTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ParseDeviceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseDeviceTokenResponse) Reset() {
	*x = ParseDeviceTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseDeviceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseDeviceTokenResponse) ProtoMessage() {}

func (x *ParseDeviceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseDeviceTokenResponse.ProtoReflect.Descriptor instead.
func (*ParseDeviceTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ParseDeviceTokenResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\"G\n" +
	"\x16CreateUserTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x01(\x05R\x05roles\"a\n" +
	"\x17CreateUserTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"V\n" +
	"\x18CreateDeviceTokenRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"1\n" +
	"\x19CreateDeviceTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\":\n" +
	"\x19CreateServiceTokenRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"2\n" +
	"\x1aCreateServiceTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"-\n" +
	"\x15ParseUserTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x83\x01\n" +
	"\x16ParseUserTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x01(\x05R\x05roles\x12\x19\n" +
	"\btoken_id\x18\x03 \x01(\tR\atokenId\x12\x1f\n" +
	"\vexprires_at\x18\x04 \x01(\x03R\n" +
	"expriresAt\"9\n" +
	"\x18ParseServiceTokenRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\":\n" +
	"\x19ParseServiceTokenResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"L\n" +
	"\x17ParseDeviceTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"7\n" +
	"\x18ParseDeviceTokenResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId2\x82\x04\n" +
	"\vAuthService\x12N\n" +
	"\x0fCreateUserToken\x12\x1c.auth.CreateUserTokenRequest\x1a\x1d.auth.CreateUserTokenResponse\x12W\n" +
	"\x12CreateServiceToken\x12\x1f.auth.CreateServiceTokenRequest\x1a .auth.CreateServiceTokenResponse\x12T\n" +
	"\x11CreateDeviceToken\x12\x1e.auth.CreateDeviceTokenRequest\x1a\x1f.auth.CreateDeviceTokenResponse\x12K\n" +
	"\x0eParseUserToken\x12\x1b.auth.ParseUserTokenRequest\x1a\x1c.auth.ParseUserTokenResponse\x12T\n" +
	"\x11ParseServiceToken\x12\x1e.auth.ParseServiceTokenRequest\x1a\x1f.auth.ParseServiceTokenResponse\x12Q\n" +
	"\x10ParseDeviceToken\x12\x1d.auth.ParseDeviceTokenRequest\x1a\x1e.auth.ParseDeviceTokenResponseBEZCgithub.com/youknow2509/cio_verify_face/server/service_auth/proto/pbb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_auth_proto_goTypes = []any{
	(*CreateUserTokenRequest)(nil),     // 0: auth.CreateUserTokenRequest
	(*CreateUserTokenResponse)(nil),    // 1: auth.CreateUserTokenResponse
	(*CreateDeviceTokenRequest)(nil),   // 2: auth.CreateDeviceTokenRequest
	(*CreateDeviceTokenResponse)(nil),  // 3: auth.CreateDeviceTokenResponse
	(*CreateServiceTokenRequest)(nil),  // 4: auth.CreateServiceTokenRequest
	(*CreateServiceTokenResponse)(nil), // 5: auth.CreateServiceTokenResponse
	(*ParseUserTokenRequest)(nil),      // 6: auth.ParseUserTokenRequest
	(*ParseUserTokenResponse)(nil),     // 7: auth.ParseUserTokenResponse
	(*ParseServiceTokenRequest)(nil),   // 8: auth.ParseServiceTokenRequest
	(*ParseServiceTokenResponse)(nil),  // 9: auth.ParseServiceTokenResponse
	(*ParseDeviceTokenRequest)(nil),    // 10: auth.ParseDeviceTokenRequest
	(*ParseDeviceTokenResponse)(nil),   // 11: auth.ParseDeviceTokenResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	0,  // 0: auth.AuthService.CreateUserToken:input_type -> auth.CreateUserTokenRequest
	4,  // 1: auth.AuthService.CreateServiceToken:input_type -> auth.CreateServiceTokenRequest
	2,  // 2: auth.AuthService.CreateDeviceToken:input_type -> auth.CreateDeviceTokenRequest
	6,  // 3: auth.AuthService.ParseUserToken:input_type -> auth.ParseUserTokenRequest
	8,  // 4: auth.AuthService.ParseServiceToken:input_type -> auth.ParseServiceTokenRequest
	10, // 5: auth.AuthService.ParseDeviceToken:input_type -> auth.ParseDeviceTokenRequest
	1,  // 6: auth.AuthService.CreateUserToken:output_type -> auth.CreateUserTokenResponse
	5,  // 7: auth.AuthService.CreateServiceToken:output_type -> auth.CreateServiceTokenResponse
	3,  // 8: auth.AuthService.CreateDeviceToken:output_type -> auth.CreateDeviceTokenResponse
	7,  // 9: auth.AuthService.ParseUserToken:output_type -> auth.ParseUserTokenResponse
	9,  // 10: auth.AuthService.ParseServiceToken:output_type -> auth.ParseServiceTokenResponse
	11, // 11: auth.AuthService.ParseDeviceToken:output_type -> auth.ParseDeviceTokenResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
