// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/ws.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        string                 `protobuf:"bytes,1,opt,name=connId,proto3" json:"connId,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_proto_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetConnId() string {
	if x != nil {
		return x.ConnId
	}
	return ""
}

func (x *MessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_ws_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ws_proto protoreflect.FileDescriptor

const file_proto_ws_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ws.proto\x12\x02pb\"B\n" +
	"\x0eMessageRequest\x12\x16\n" +
	"\x06connId\x18\x01 \x01(\tR\x06connId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"I\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2H\n" +
	"\n" +
	"Dispatcher\x12:\n" +
	"\vSendMessage\x12\x12.pb.MessageRequest\x1a\x17.pb.SendMessageResponseB\aZ\x05./genb\x06proto3"

var (
	file_proto_ws_proto_rawDescOnce sync.Once
	file_proto_ws_proto_rawDescData []byte
)

func file_proto_ws_proto_rawDescGZIP() []byte {
	file_proto_ws_proto_rawDescOnce.Do(func() {
		file_proto_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)))
	})
	return file_proto_ws_proto_rawDescData
}

var file_proto_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ws_proto_goTypes = []any{
	(*MessageRequest)(nil),      // 0: pb.MessageRequest
	(*SendMessageResponse)(nil), // 1: pb.SendMessageResponse
}
var file_proto_ws_proto_depIdxs = []int32{
	0, // 0: pb.Dispatcher.SendMessage:input_type -> pb.MessageRequest
	1, // 1: pb.Dispatcher.SendMessage:output_type -> pb.SendMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ws_proto_init() }
func file_proto_ws_proto_init() {
	if File_proto_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ws_proto_rawDesc), len(file_proto_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ws_proto_goTypes,
		DependencyIndexes: file_proto_ws_proto_depIdxs,
		MessageInfos:      file_proto_ws_proto_msgTypes,
	}.Build()
	File_proto_ws_proto = out.File
	file_proto_ws_proto_goTypes = nil
	file_proto_ws_proto_depIdxs = nil
}
