// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: attendance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAttendanceRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*AttendanceRecord    `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceRecordsResponse) Reset() {
	*x = GetAttendanceRecordsResponse{}
	mi := &file_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceRecordsResponse) ProtoMessage() {}

func (x *GetAttendanceRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceRecordsResponse.ProtoReflect.Descriptor instead.
func (*GetAttendanceRecordsResponse) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *GetAttendanceRecordsResponse) GetRecords() []*AttendanceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetAttendanceRecordsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAttendanceRecordsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type AttendanceRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CheckType          string                 `protobuf:"bytes,3,opt,name=check_type,json=checkType,proto3" json:"check_type,omitempty"` // "check_in" or "check_out"
	Timestamp          int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location           string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	VerificationMethod string                 `protobuf:"bytes,6,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	VerificationScore  float32                `protobuf:"fixed32,7,opt,name=verification_score,json=verificationScore,proto3" json:"verification_score,omitempty"`
	FaceImageUrl       string                 `protobuf:"bytes,8,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AttendanceRecord) Reset() {
	*x = AttendanceRecord{}
	mi := &file_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceRecord) ProtoMessage() {}

func (x *AttendanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceRecord.ProtoReflect.Descriptor instead.
func (*AttendanceRecord) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *AttendanceRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AttendanceRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AttendanceRecord) GetCheckType() string {
	if x != nil {
		return x.CheckType
	}
	return ""
}

func (x *AttendanceRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AttendanceRecord) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *AttendanceRecord) GetVerificationMethod() string {
	if x != nil {
		return x.VerificationMethod
	}
	return ""
}

func (x *AttendanceRecord) GetVerificationScore() float32 {
	if x != nil {
		return x.VerificationScore
	}
	return 0
}

func (x *AttendanceRecord) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

type GetAttendanceRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	StartDate     int64                  `protobuf:"varint,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,5,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceRecordsRequest) Reset() {
	*x = GetAttendanceRecordsRequest{}
	mi := &file_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceRecordsRequest) ProtoMessage() {}

func (x *GetAttendanceRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceRecordsRequest.ProtoReflect.Descriptor instead.
func (*GetAttendanceRecordsRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttendanceRecordsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetAttendanceRecordsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetAttendanceRecordsRequest) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *GetAttendanceRecordsRequest) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *GetAttendanceRecordsRequest) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

type CheckIOAttendanceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo        *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Location           string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	VerificationMethod string                 `protobuf:"bytes,4,opt,name=verification_method,json=verificationMethod,proto3" json:"verification_method,omitempty"`
	VerificationScore  float32                `protobuf:"fixed32,5,opt,name=verification_score,json=verificationScore,proto3" json:"verification_score,omitempty"`
	FaceImageUrl       string                 `protobuf:"bytes,6,opt,name=face_image_url,json=faceImageUrl,proto3" json:"face_image_url,omitempty"`
	RecordedAt         int64                  `protobuf:"varint,7,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckIOAttendanceRequest) Reset() {
	*x = CheckIOAttendanceRequest{}
	mi := &file_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIOAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIOAttendanceRequest) ProtoMessage() {}

func (x *CheckIOAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIOAttendanceRequest.ProtoReflect.Descriptor instead.
func (*CheckIOAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{3}
}

func (x *CheckIOAttendanceRequest) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *CheckIOAttendanceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CheckIOAttendanceRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CheckIOAttendanceRequest) GetVerificationMethod() string {
	if x != nil {
		return x.VerificationMethod
	}
	return ""
}

func (x *CheckIOAttendanceRequest) GetVerificationScore() float32 {
	if x != nil {
		return x.VerificationScore
	}
	return 0
}

func (x *CheckIOAttendanceRequest) GetFaceImageUrl() string {
	if x != nil {
		return x.FaceImageUrl
	}
	return ""
}

func (x *CheckIOAttendanceRequest) GetRecordedAt() int64 {
	if x != nil {
		return x.RecordedAt
	}
	return 0
}

type ResponseBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBase) Reset() {
	*x = ResponseBase{}
	mi := &file_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBase) ProtoMessage() {}

func (x *ResponseBase) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBase.ProtoReflect.Descriptor instead.
func (*ResponseBase) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseBase) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ResponseBase) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientAgent   string                 `protobuf:"bytes,5,opt,name=client_agent,json=clientAgent,proto3" json:"client_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_attendance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_attendance_proto_rawDescGZIP(), []int{5}
}

func (x *SessionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionInfo) GetClientAgent() string {
	if x != nil {
		return x.ClientAgent
	}
	return ""
}

var File_attendance_proto protoreflect.FileDescriptor

const file_attendance_proto_rawDesc = "" +
	"\n" +
	"\x10attendance.proto\x12\n" +
	"attendance\"\x89\x01\n" +
	"\x1cGetAttendanceRecordsResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.attendance.AttendanceRecordR\arecords\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"\xa7\x02\n" +
	"\x10AttendanceRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"check_type\x18\x03 \x01(\tR\tcheckType\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12/\n" +
	"\x13verification_method\x18\x06 \x01(\tR\x12verificationMethod\x12-\n" +
	"\x12verification_score\x18\a \x01(\x02R\x11verificationScore\x12$\n" +
	"\x0eface_image_url\x18\b \x01(\tR\ffaceImageUrl\"\xcf\x01\n" +
	"\x1bGetAttendanceRecordsRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\x12:\n" +
	"\fsession_info\x18\x05 \x01(\v2\x17.attendance.SessionInfoR\vsessionInfo\"\xb6\x02\n" +
	"\x18CheckIOAttendanceRequest\x12:\n" +
	"\fsession_info\x18\x01 \x01(\v2\x17.attendance.SessionInfoR\vsessionInfo\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12/\n" +
	"\x13verification_method\x18\x04 \x01(\tR\x12verificationMethod\x12-\n" +
	"\x12verification_score\x18\x05 \x01(\x02R\x11verificationScore\x12$\n" +
	"\x0eface_image_url\x18\x06 \x01(\tR\ffaceImageUrl\x12\x1f\n" +
	"\vrecorded_at\x18\a \x01(\x03R\n" +
	"recordedAt\"A\n" +
	"\fResponseBase\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\"\x99\x01\n" +
	"\vSessionInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12!\n" +
	"\fclient_agent\x18\x05 \x01(\tR\vclientAgent2\xa9\x02\n" +
	"\x11AttendanceService\x12S\n" +
	"\x11CheckInAttendance\x12$.attendance.CheckIOAttendanceRequest\x1a\x18.attendance.ResponseBase\x12T\n" +
	"\x12CheckOutAttendance\x12$.attendance.CheckIOAttendanceRequest\x1a\x18.attendance.ResponseBase\x12i\n" +
	"\x14GetAttendanceRecords\x12'.attendance.GetAttendanceRecordsRequest\x1a(.attendance.GetAttendanceRecordsResponseBKZIgithub.com/youknow2509/cio_verify_face/server/service_attendance/proto/pbb\x06proto3"

var (
	file_attendance_proto_rawDescOnce sync.Once
	file_attendance_proto_rawDescData []byte
)

func file_attendance_proto_rawDescGZIP() []byte {
	file_attendance_proto_rawDescOnce.Do(func() {
		file_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)))
	})
	return file_attendance_proto_rawDescData
}

var file_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_attendance_proto_goTypes = []any{
	(*GetAttendanceRecordsResponse)(nil), // 0: attendance.GetAttendanceRecordsResponse
	(*AttendanceRecord)(nil),             // 1: attendance.AttendanceRecord
	(*GetAttendanceRecordsRequest)(nil),  // 2: attendance.GetAttendanceRecordsRequest
	(*CheckIOAttendanceRequest)(nil),     // 3: attendance.CheckIOAttendanceRequest
	(*ResponseBase)(nil),                 // 4: attendance.ResponseBase
	(*SessionInfo)(nil),                  // 5: attendance.SessionInfo
}
var file_attendance_proto_depIdxs = []int32{
	1, // 0: attendance.GetAttendanceRecordsResponse.records:type_name -> attendance.AttendanceRecord
	5, // 1: attendance.GetAttendanceRecordsRequest.session_info:type_name -> attendance.SessionInfo
	5, // 2: attendance.CheckIOAttendanceRequest.session_info:type_name -> attendance.SessionInfo
	3, // 3: attendance.AttendanceService.CheckInAttendance:input_type -> attendance.CheckIOAttendanceRequest
	3, // 4: attendance.AttendanceService.CheckOutAttendance:input_type -> attendance.CheckIOAttendanceRequest
	2, // 5: attendance.AttendanceService.GetAttendanceRecords:input_type -> attendance.GetAttendanceRecordsRequest
	4, // 6: attendance.AttendanceService.CheckInAttendance:output_type -> attendance.ResponseBase
	4, // 7: attendance.AttendanceService.CheckOutAttendance:output_type -> attendance.ResponseBase
	0, // 8: attendance.AttendanceService.GetAttendanceRecords:output_type -> attendance.GetAttendanceRecordsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_attendance_proto_init() }
func file_attendance_proto_init() {
	if File_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendance_proto_rawDesc), len(file_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendance_proto_goTypes,
		DependencyIndexes: file_attendance_proto_depIdxs,
		MessageInfos:      file_attendance_proto_msgTypes,
	}.Build()
	File_attendance_proto = out.File
	file_attendance_proto_goTypes = nil
	file_attendance_proto_depIdxs = nil
}
