// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.33.0
// source: proto/attendance.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AttendanceService_AddAttendance_FullMethodName                     = "/attendance.AttendanceService/AddAttendance"
	AttendanceService_GetAttendanceRecords_FullMethodName              = "/attendance.AttendanceService/GetAttendanceRecords"
	AttendanceService_GetAttendanceRecordsEmployee_FullMethodName      = "/attendance.AttendanceService/GetAttendanceRecordsEmployee"
	AttendanceService_GetDailyAttendanceSummary_FullMethodName         = "/attendance.AttendanceService/GetDailyAttendanceSummary"
	AttendanceService_GetDailyAttendanceSummaryEmployee_FullMethodName = "/attendance.AttendanceService/GetDailyAttendanceSummaryEmployee"
	AttendanceService_AddBatchAttendance_FullMethodName                = "/attendance.AttendanceService/AddBatchAttendance"
	AttendanceService_ServiceAddBatchAttendance_FullMethodName         = "/attendance.AttendanceService/ServiceAddBatchAttendance"
)

// AttendanceServiceClient is the client API for AttendanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Attendance service for inter-service communication
type AttendanceServiceClient interface {
	AddAttendance(ctx context.Context, in *AddAttendanceInput, opts ...grpc.CallOption) (*AddAttendanceOutput, error)
	GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsInput, opts ...grpc.CallOption) (*GetAttendanceRecordsOutput, error)
	GetAttendanceRecordsEmployee(ctx context.Context, in *GetAttendanceRecordsEmployeeInput, opts ...grpc.CallOption) (*GetAttendanceRecordsOutput, error)
	GetDailyAttendanceSummary(ctx context.Context, in *GetDailyAttendanceSummaryInput, opts ...grpc.CallOption) (*GetDailyAttendanceSummaryOutput, error)
	GetDailyAttendanceSummaryEmployee(ctx context.Context, in *GetDailyAttendanceSummaryEmployeeInput, opts ...grpc.CallOption) (*GetDailyAttendanceSummaryOutput, error)
	AddBatchAttendance(ctx context.Context, opts ...grpc.CallOption) (AttendanceService_AddBatchAttendanceClient, error)
	ServiceAddBatchAttendance(ctx context.Context, opts ...grpc.CallOption) (AttendanceService_ServiceAddBatchAttendanceClient, error)
}

type attendanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceServiceClient(cc grpc.ClientConnInterface) AttendanceServiceClient {
	return &attendanceServiceClient{cc}
}

func (c *attendanceServiceClient) AddAttendance(ctx context.Context, in *AddAttendanceInput, opts ...grpc.CallOption) (*AddAttendanceOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAttendanceOutput)
	err := c.cc.Invoke(ctx, AttendanceService_AddAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsInput, opts ...grpc.CallOption) (*GetAttendanceRecordsOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsOutput)
	err := c.cc.Invoke(ctx, AttendanceService_GetAttendanceRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) GetAttendanceRecordsEmployee(ctx context.Context, in *GetAttendanceRecordsEmployeeInput, opts ...grpc.CallOption) (*GetAttendanceRecordsOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsOutput)
	err := c.cc.Invoke(ctx, AttendanceService_GetAttendanceRecordsEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) GetDailyAttendanceSummary(ctx context.Context, in *GetDailyAttendanceSummaryInput, opts ...grpc.CallOption) (*GetDailyAttendanceSummaryOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyAttendanceSummaryOutput)
	err := c.cc.Invoke(ctx, AttendanceService_GetDailyAttendanceSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) GetDailyAttendanceSummaryEmployee(ctx context.Context, in *GetDailyAttendanceSummaryEmployeeInput, opts ...grpc.CallOption) (*GetDailyAttendanceSummaryOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyAttendanceSummaryOutput)
	err := c.cc.Invoke(ctx, AttendanceService_GetDailyAttendanceSummaryEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) AddBatchAttendance(ctx context.Context, opts ...grpc.CallOption) (AttendanceService_AddBatchAttendanceClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttendanceService_ServiceDesc.Streams[0], AttendanceService_AddBatchAttendance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &attendanceServiceAddBatchAttendanceClient{ClientStream: stream}
	return x, nil
}

type AttendanceService_AddBatchAttendanceClient interface {
	Send(*AddAttendanceInput) error
	CloseAndRecv() (*AddAttendanceOutput, error)
	grpc.ClientStream
}

type attendanceServiceAddBatchAttendanceClient struct {
	grpc.ClientStream
}

func (x *attendanceServiceAddBatchAttendanceClient) Send(m *AddAttendanceInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *attendanceServiceAddBatchAttendanceClient) CloseAndRecv() (*AddAttendanceOutput, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddAttendanceOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *attendanceServiceClient) ServiceAddBatchAttendance(ctx context.Context, opts ...grpc.CallOption) (AttendanceService_ServiceAddBatchAttendanceClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AttendanceService_ServiceDesc.Streams[1], AttendanceService_ServiceAddBatchAttendance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &attendanceServiceServiceAddBatchAttendanceClient{ClientStream: stream}
	return x, nil
}

type AttendanceService_ServiceAddBatchAttendanceClient interface {
	Send(*ServiceAddBatchAttendanceInput) error
	CloseAndRecv() (*AddAttendanceOutput, error)
	grpc.ClientStream
}

type attendanceServiceServiceAddBatchAttendanceClient struct {
	grpc.ClientStream
}

func (x *attendanceServiceServiceAddBatchAttendanceClient) Send(m *ServiceAddBatchAttendanceInput) error {
	return x.ClientStream.SendMsg(m)
}

func (x *attendanceServiceServiceAddBatchAttendanceClient) CloseAndRecv() (*AddAttendanceOutput, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddAttendanceOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AttendanceServiceServer is the server API for AttendanceService service.
// All implementations must embed UnimplementedAttendanceServiceServer
// for forward compatibility
//
// Attendance service for inter-service communication
type AttendanceServiceServer interface {
	AddAttendance(context.Context, *AddAttendanceInput) (*AddAttendanceOutput, error)
	GetAttendanceRecords(context.Context, *GetAttendanceRecordsInput) (*GetAttendanceRecordsOutput, error)
	GetAttendanceRecordsEmployee(context.Context, *GetAttendanceRecordsEmployeeInput) (*GetAttendanceRecordsOutput, error)
	GetDailyAttendanceSummary(context.Context, *GetDailyAttendanceSummaryInput) (*GetDailyAttendanceSummaryOutput, error)
	GetDailyAttendanceSummaryEmployee(context.Context, *GetDailyAttendanceSummaryEmployeeInput) (*GetDailyAttendanceSummaryOutput, error)
	AddBatchAttendance(AttendanceService_AddBatchAttendanceServer) error
	ServiceAddBatchAttendance(AttendanceService_ServiceAddBatchAttendanceServer) error
	mustEmbedUnimplementedAttendanceServiceServer()
}

// UnimplementedAttendanceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAttendanceServiceServer struct {
}

func (UnimplementedAttendanceServiceServer) AddAttendance(context.Context, *AddAttendanceInput) (*AddAttendanceOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttendance not implemented")
}
func (UnimplementedAttendanceServiceServer) GetAttendanceRecords(context.Context, *GetAttendanceRecordsInput) (*GetAttendanceRecordsOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecords not implemented")
}
func (UnimplementedAttendanceServiceServer) GetAttendanceRecordsEmployee(context.Context, *GetAttendanceRecordsEmployeeInput) (*GetAttendanceRecordsOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecordsEmployee not implemented")
}
func (UnimplementedAttendanceServiceServer) GetDailyAttendanceSummary(context.Context, *GetDailyAttendanceSummaryInput) (*GetDailyAttendanceSummaryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyAttendanceSummary not implemented")
}
func (UnimplementedAttendanceServiceServer) GetDailyAttendanceSummaryEmployee(context.Context, *GetDailyAttendanceSummaryEmployeeInput) (*GetDailyAttendanceSummaryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyAttendanceSummaryEmployee not implemented")
}
func (UnimplementedAttendanceServiceServer) AddBatchAttendance(AttendanceService_AddBatchAttendanceServer) error {
	return status.Errorf(codes.Unimplemented, "method AddBatchAttendance not implemented")
}
func (UnimplementedAttendanceServiceServer) ServiceAddBatchAttendance(AttendanceService_ServiceAddBatchAttendanceServer) error {
	return status.Errorf(codes.Unimplemented, "method ServiceAddBatchAttendance not implemented")
}
func (UnimplementedAttendanceServiceServer) mustEmbedUnimplementedAttendanceServiceServer() {}

// UnsafeAttendanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceServiceServer will
// result in compilation errors.
type UnsafeAttendanceServiceServer interface {
	mustEmbedUnimplementedAttendanceServiceServer()
}

func RegisterAttendanceServiceServer(s grpc.ServiceRegistrar, srv AttendanceServiceServer) {
	s.RegisterService(&AttendanceService_ServiceDesc, srv)
}

func _AttendanceService_AddAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttendanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).AddAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_AddAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).AddAttendance(ctx, req.(*AddAttendanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_GetAttendanceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).GetAttendanceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_GetAttendanceRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).GetAttendanceRecords(ctx, req.(*GetAttendanceRecordsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_GetAttendanceRecordsEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsEmployeeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).GetAttendanceRecordsEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_GetAttendanceRecordsEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).GetAttendanceRecordsEmployee(ctx, req.(*GetAttendanceRecordsEmployeeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_GetDailyAttendanceSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyAttendanceSummaryInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).GetDailyAttendanceSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_GetDailyAttendanceSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).GetDailyAttendanceSummary(ctx, req.(*GetDailyAttendanceSummaryInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_GetDailyAttendanceSummaryEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyAttendanceSummaryEmployeeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).GetDailyAttendanceSummaryEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_GetDailyAttendanceSummaryEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).GetDailyAttendanceSummaryEmployee(ctx, req.(*GetDailyAttendanceSummaryEmployeeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_AddBatchAttendance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AttendanceServiceServer).AddBatchAttendance(&attendanceServiceAddBatchAttendanceServer{ServerStream: stream})
}

type AttendanceService_AddBatchAttendanceServer interface {
	SendAndClose(*AddAttendanceOutput) error
	Recv() (*AddAttendanceInput, error)
	grpc.ServerStream
}

type attendanceServiceAddBatchAttendanceServer struct {
	grpc.ServerStream
}

func (x *attendanceServiceAddBatchAttendanceServer) SendAndClose(m *AddAttendanceOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *attendanceServiceAddBatchAttendanceServer) Recv() (*AddAttendanceInput, error) {
	m := new(AddAttendanceInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AttendanceService_ServiceAddBatchAttendance_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AttendanceServiceServer).ServiceAddBatchAttendance(&attendanceServiceServiceAddBatchAttendanceServer{ServerStream: stream})
}

type AttendanceService_ServiceAddBatchAttendanceServer interface {
	SendAndClose(*AddAttendanceOutput) error
	Recv() (*ServiceAddBatchAttendanceInput, error)
	grpc.ServerStream
}

type attendanceServiceServiceAddBatchAttendanceServer struct {
	grpc.ServerStream
}

func (x *attendanceServiceServiceAddBatchAttendanceServer) SendAndClose(m *AddAttendanceOutput) error {
	return x.ServerStream.SendMsg(m)
}

func (x *attendanceServiceServiceAddBatchAttendanceServer) Recv() (*ServiceAddBatchAttendanceInput, error) {
	m := new(ServiceAddBatchAttendanceInput)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AttendanceService_ServiceDesc is the grpc.ServiceDesc for AttendanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attendance.AttendanceService",
	HandlerType: (*AttendanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAttendance",
			Handler:    _AttendanceService_AddAttendance_Handler,
		},
		{
			MethodName: "GetAttendanceRecords",
			Handler:    _AttendanceService_GetAttendanceRecords_Handler,
		},
		{
			MethodName: "GetAttendanceRecordsEmployee",
			Handler:    _AttendanceService_GetAttendanceRecordsEmployee_Handler,
		},
		{
			MethodName: "GetDailyAttendanceSummary",
			Handler:    _AttendanceService_GetDailyAttendanceSummary_Handler,
		},
		{
			MethodName: "GetDailyAttendanceSummaryEmployee",
			Handler:    _AttendanceService_GetDailyAttendanceSummaryEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddBatchAttendance",
			Handler:       _AttendanceService_AddBatchAttendance_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServiceAddBatchAttendance",
			Handler:       _AttendanceService_ServiceAddBatchAttendance_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/attendance.proto",
}
