// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: attendance.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttendanceService_CheckInAttendance_FullMethodName    = "/attendance.AttendanceService/CheckInAttendance"
	AttendanceService_CheckOutAttendance_FullMethodName   = "/attendance.AttendanceService/CheckOutAttendance"
	AttendanceService_GetAttendanceRecords_FullMethodName = "/attendance.AttendanceService/GetAttendanceRecords"
)

// AttendanceServiceClient is the client API for AttendanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Attendance service for inter-service communication
type AttendanceServiceClient interface {
	// Check in attendance
	CheckInAttendance(ctx context.Context, in *CheckIOAttendanceRequest, opts ...grpc.CallOption) (*ResponseBase, error)
	// Check out attendance
	CheckOutAttendance(ctx context.Context, in *CheckIOAttendanceRequest, opts ...grpc.CallOption) (*ResponseBase, error)
	// Get attendance records within a date range for company
	GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error)
}

type attendanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttendanceServiceClient(cc grpc.ClientConnInterface) AttendanceServiceClient {
	return &attendanceServiceClient{cc}
}

func (c *attendanceServiceClient) CheckInAttendance(ctx context.Context, in *CheckIOAttendanceRequest, opts ...grpc.CallOption) (*ResponseBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBase)
	err := c.cc.Invoke(ctx, AttendanceService_CheckInAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) CheckOutAttendance(ctx context.Context, in *CheckIOAttendanceRequest, opts ...grpc.CallOption) (*ResponseBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBase)
	err := c.cc.Invoke(ctx, AttendanceService_CheckOutAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attendanceServiceClient) GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsResponse)
	err := c.cc.Invoke(ctx, AttendanceService_GetAttendanceRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceServiceServer is the server API for AttendanceService service.
// All implementations must embed UnimplementedAttendanceServiceServer
// for forward compatibility.
//
// Attendance service for inter-service communication
type AttendanceServiceServer interface {
	// Check in attendance
	CheckInAttendance(context.Context, *CheckIOAttendanceRequest) (*ResponseBase, error)
	// Check out attendance
	CheckOutAttendance(context.Context, *CheckIOAttendanceRequest) (*ResponseBase, error)
	// Get attendance records within a date range for company
	GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*GetAttendanceRecordsResponse, error)
	mustEmbedUnimplementedAttendanceServiceServer()
}

// UnimplementedAttendanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttendanceServiceServer struct{}

func (UnimplementedAttendanceServiceServer) CheckInAttendance(context.Context, *CheckIOAttendanceRequest) (*ResponseBase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckInAttendance not implemented")
}
func (UnimplementedAttendanceServiceServer) CheckOutAttendance(context.Context, *CheckIOAttendanceRequest) (*ResponseBase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckOutAttendance not implemented")
}
func (UnimplementedAttendanceServiceServer) GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*GetAttendanceRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecords not implemented")
}
func (UnimplementedAttendanceServiceServer) mustEmbedUnimplementedAttendanceServiceServer() {}
func (UnimplementedAttendanceServiceServer) testEmbeddedByValue()                           {}

// UnsafeAttendanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttendanceServiceServer will
// result in compilation errors.
type UnsafeAttendanceServiceServer interface {
	mustEmbedUnimplementedAttendanceServiceServer()
}

func RegisterAttendanceServiceServer(s grpc.ServiceRegistrar, srv AttendanceServiceServer) {
	// If the following call pancis, it indicates UnimplementedAttendanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttendanceService_ServiceDesc, srv)
}

func _AttendanceService_CheckInAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIOAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).CheckInAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_CheckInAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).CheckInAttendance(ctx, req.(*CheckIOAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_CheckOutAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIOAttendanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).CheckOutAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_CheckOutAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).CheckOutAttendance(ctx, req.(*CheckIOAttendanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttendanceService_GetAttendanceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceServiceServer).GetAttendanceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttendanceService_GetAttendanceRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceServiceServer).GetAttendanceRecords(ctx, req.(*GetAttendanceRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttendanceService_ServiceDesc is the grpc.ServiceDesc for AttendanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttendanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attendance.AttendanceService",
	HandlerType: (*AttendanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckInAttendance",
			Handler:    _AttendanceService_CheckInAttendance_Handler,
		},
		{
			MethodName: "CheckOutAttendance",
			Handler:    _AttendanceService_CheckOutAttendance_Handler,
		},
		{
			MethodName: "GetAttendanceRecords",
			Handler:    _AttendanceService_GetAttendanceRecords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "attendance.proto",
}
