// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.33.0
// source: proto/auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AuthService_CreateUserToken_FullMethodName    = "/auth.AuthService/CreateUserToken"
	AuthService_CreateServiceToken_FullMethodName = "/auth.AuthService/CreateServiceToken"
	AuthService_CreateDeviceToken_FullMethodName  = "/auth.AuthService/CreateDeviceToken"
	AuthService_ParseUserToken_FullMethodName     = "/auth.AuthService/ParseUserToken"
	AuthService_ParseServiceToken_FullMethodName  = "/auth.AuthService/ParseServiceToken"
	AuthService_ParseDeviceToken_FullMethodName   = "/auth.AuthService/ParseDeviceToken"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth service for inter-service communication
type AuthServiceClient interface {
	CreateUserToken(ctx context.Context, in *CreateUserTokenRequest, opts ...grpc.CallOption) (*CreateUserTokenResponse, error)
	CreateServiceToken(ctx context.Context, in *CreateServiceTokenRequest, opts ...grpc.CallOption) (*CreateServiceTokenResponse, error)
	CreateDeviceToken(ctx context.Context, in *CreateDeviceTokenRequest, opts ...grpc.CallOption) (*CreateDeviceTokenResponse, error)
	ParseUserToken(ctx context.Context, in *ParseUserTokenRequest, opts ...grpc.CallOption) (*ParseUserTokenResponse, error)
	ParseServiceToken(ctx context.Context, in *ParseServiceTokenRequest, opts ...grpc.CallOption) (*ParseServiceTokenResponse, error)
	ParseDeviceToken(ctx context.Context, in *ParseDeviceTokenRequest, opts ...grpc.CallOption) (*ParseDeviceTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CreateUserToken(ctx context.Context, in *CreateUserTokenRequest, opts ...grpc.CallOption) (*CreateUserTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateServiceToken(ctx context.Context, in *CreateServiceTokenRequest, opts ...grpc.CallOption) (*CreateServiceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateDeviceToken(ctx context.Context, in *CreateDeviceTokenRequest, opts ...grpc.CallOption) (*CreateDeviceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeviceTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateDeviceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ParseUserToken(ctx context.Context, in *ParseUserTokenRequest, opts ...grpc.CallOption) (*ParseUserTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseUserTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ParseUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ParseServiceToken(ctx context.Context, in *ParseServiceTokenRequest, opts ...grpc.CallOption) (*ParseServiceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseServiceTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ParseServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ParseDeviceToken(ctx context.Context, in *ParseDeviceTokenRequest, opts ...grpc.CallOption) (*ParseDeviceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDeviceTokenResponse)
	err := c.cc.Invoke(ctx, AuthService_ParseDeviceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility
//
// Auth service for inter-service communication
type AuthServiceServer interface {
	CreateUserToken(context.Context, *CreateUserTokenRequest) (*CreateUserTokenResponse, error)
	CreateServiceToken(context.Context, *CreateServiceTokenRequest) (*CreateServiceTokenResponse, error)
	CreateDeviceToken(context.Context, *CreateDeviceTokenRequest) (*CreateDeviceTokenResponse, error)
	ParseUserToken(context.Context, *ParseUserTokenRequest) (*ParseUserTokenResponse, error)
	ParseServiceToken(context.Context, *ParseServiceTokenRequest) (*ParseServiceTokenResponse, error)
	ParseDeviceToken(context.Context, *ParseDeviceTokenRequest) (*ParseDeviceTokenResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) CreateUserToken(context.Context, *CreateUserTokenRequest) (*CreateUserTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserToken not implemented")
}
func (UnimplementedAuthServiceServer) CreateServiceToken(context.Context, *CreateServiceTokenRequest) (*CreateServiceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServiceToken not implemented")
}
func (UnimplementedAuthServiceServer) CreateDeviceToken(context.Context, *CreateDeviceTokenRequest) (*CreateDeviceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceToken not implemented")
}
func (UnimplementedAuthServiceServer) ParseUserToken(context.Context, *ParseUserTokenRequest) (*ParseUserTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseUserToken not implemented")
}
func (UnimplementedAuthServiceServer) ParseServiceToken(context.Context, *ParseServiceTokenRequest) (*ParseServiceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseServiceToken not implemented")
}
func (UnimplementedAuthServiceServer) ParseDeviceToken(context.Context, *ParseDeviceTokenRequest) (*ParseDeviceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ParseDeviceToken not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_CreateUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateUserToken(ctx, req.(*CreateUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateServiceToken(ctx, req.(*CreateServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateDeviceToken(ctx, req.(*CreateDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ParseUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ParseUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ParseUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ParseUserToken(ctx, req.(*ParseUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ParseServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ParseServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ParseServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ParseServiceToken(ctx, req.(*ParseServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ParseDeviceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDeviceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ParseDeviceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ParseDeviceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ParseDeviceToken(ctx, req.(*ParseDeviceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserToken",
			Handler:    _AuthService_CreateUserToken_Handler,
		},
		{
			MethodName: "CreateServiceToken",
			Handler:    _AuthService_CreateServiceToken_Handler,
		},
		{
			MethodName: "CreateDeviceToken",
			Handler:    _AuthService_CreateDeviceToken_Handler,
		},
		{
			MethodName: "ParseUserToken",
			Handler:    _AuthService_ParseUserToken_Handler,
		},
		{
			MethodName: "ParseServiceToken",
			Handler:    _AuthService_ParseServiceToken_Handler,
		},
		{
			MethodName: "ParseDeviceToken",
			Handler:    _AuthService_ParseDeviceToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
