package start

import (
	"fmt"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files" // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/youknow2509/cio_verify_face/server/service_auth/cmd/swag/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/youknow2509/cio_verify_face/server/service_auth/internal/global"
	httpRouter "github.com/youknow2509/cio_verify_face/server/service_auth/internal/interfaces/http/router"
	domainConfig "github.com/youknow2509/cio_verify_face/server/service_auth/internal/domain/config"
	infraMiddleware "github.com/youknow2509/cio_verify_face/server/service_auth/internal/infrastructure/middleware"
)

func initGinRouter(setting *domainConfig.ServerSetting) error {
	ginEngine := gin.Default()
	// Set Gin mode
	if setting.Mode != "dev" {
		gin.SetMode(gin.ReleaseMode)
	} else {
		gin.SetMode(gin.DebugMode)
		ginEngine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}
	// Set port for Gin
	portGin := fmt.Sprintf(":%d", setting.Port)

	// Initialize routes
	if err := initRouter(ginEngine); err != nil {
		return err
	}
	// Start Gin server
	global.WaitGroup.Add(1)
	go func() {
		defer global.WaitGroup.Done()
		err := ginEngine.Run(portGin)
		if err != nil {
			global.Logger.Error(err.Error())
		}
	}()

	return nil
}

func initRouter(ginEngine *gin.Engine) error {
	// global middleware
	ginEngine.Use(cors.Default()) // TODO: customize CORS settings - Now allow all origins
	ginEngine.Use(infraMiddleware.GetValidateMiddleware().Apply())
	// Initialize routes
	httpRouter := httpRouter.HttpRouterManager{}
	apiHttpRouter := ginEngine.Group("/api")
	{
		httpRouter.AuthRouter.InitializeAuthRoutes(apiHttpRouter)
	}
	return nil
}
