package start

import (
	"fmt"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files" // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/youknow2509/cio_verify_face/server/service_auth/cmd/swag/docs" // docs is generated by Swag CLI, you have to import it.
	domainConfig "github.com/youknow2509/cio_verify_face/server/service_auth/internal/domain/config"
	"github.com/youknow2509/cio_verify_face/server/service_auth/internal/global"
	infraMiddleware "github.com/youknow2509/cio_verify_face/server/service_auth/internal/infrastructure/middleware"
	httpRouter "github.com/youknow2509/cio_verify_face/server/service_auth/internal/interfaces/http/router"
)

func initGinRouter(setting *domainConfig.ServerSetting) error {
	var ginEngine *gin.Engine
	// Set Gin mode
	if setting.Mode != "dev" {
		gin.SetMode(gin.ReleaseMode)
		ginEngine = gin.New()
	} else {
		gin.SetMode(gin.DebugMode)
		gin.ForceConsoleColor()
		ginEngine = gin.Default()
		ginEngine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	}

	// Set port for Gin
	portGin := fmt.Sprintf(":%d", setting.Port)

	// Initialize routes
	if err := initRouter(ginEngine); err != nil {
		return err
	}
	// Start Gin server
	global.WaitGroup.Add(1)
	go func() {
		defer global.WaitGroup.Done()
		err := ginEngine.Run(portGin)
		if err != nil {
			global.Logger.Error(err.Error())
		}
	}()

	return nil
}

func initRouter(ginEngine *gin.Engine) error {
	// global middleware
	ginEngine.Use(getConfigCors())
	ginEngine.Use(infraMiddleware.GetValidateMiddleware().Apply())
	
	// Add observability middleware (metrics and tracing)
	if metrics := GetHTTPMetrics(); metrics != nil {
		ginEngine.Use(metrics.GinMiddleware())
	}
	if tp := GetTracerProvider(); tp != nil {
		ginEngine.Use(tp.GinTracingMiddleware())
	}
	
	// Initialize routes
	httpRouter := httpRouter.HttpRouterManager{}
	apiHttpRouter := ginEngine.Group("/api")
	{
		httpRouter.AuthRouter.InitializeAuthRoutes(apiHttpRouter)
	}
	// Health check endpoint
	ginEngine.GET("/health", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"status": "ok",
		})
	})
	return nil
}

func getConfigCors() gin.HandlerFunc {
	corsConfig := cors.Config{
		AllowAllOrigins:  true,
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"},
		AllowHeaders:     []string{"*"}, // allow all request headers
		ExposeHeaders:    []string{"Content-Length", "Content-Type", "Authorization"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}
	return cors.New(corsConfig)
}
