// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/analytic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDailyReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                               // YYYY-MM-DD
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`    // Required
	LocationId    string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReportRequest) Reset() {
	*x = GetDailyReportRequest{}
	mi := &file_proto_analytic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportRequest) ProtoMessage() {}

func (x *GetDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportRequest.ProtoReflect.Descriptor instead.
func (*GetDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailyReportRequest) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *GetDailyReportRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDailyReportRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetDailyReportRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type GetDailyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *DailyReportData       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailyReportResponse) Reset() {
	*x = GetDailyReportResponse{}
	mi := &file_proto_analytic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportResponse) ProtoMessage() {}

func (x *GetDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportResponse.ProtoReflect.Descriptor instead.
func (*GetDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailyReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetDailyReportResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetDailyReportResponse) GetData() *DailyReportData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DailyReportData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Date                string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	TotalEmployees      int32                  `protobuf:"varint,2,opt,name=total_employees,json=totalEmployees,proto3" json:"total_employees,omitempty"`
	PresentEmployees    int32                  `protobuf:"varint,3,opt,name=present_employees,json=presentEmployees,proto3" json:"present_employees,omitempty"`
	LateEmployees       int32                  `protobuf:"varint,4,opt,name=late_employees,json=lateEmployees,proto3" json:"late_employees,omitempty"`
	EarlyLeaveEmployees int32                  `protobuf:"varint,5,opt,name=early_leave_employees,json=earlyLeaveEmployees,proto3" json:"early_leave_employees,omitempty"`
	AbsentEmployees     int32                  `protobuf:"varint,6,opt,name=absent_employees,json=absentEmployees,proto3" json:"absent_employees,omitempty"`
	AttendanceRate      float64                `protobuf:"fixed64,7,opt,name=attendance_rate,json=attendanceRate,proto3" json:"attendance_rate,omitempty"`
	Departments         []*DepartmentReport    `protobuf:"bytes,8,rep,name=departments,proto3" json:"departments,omitempty"`
	Shifts              []*ShiftReport         `protobuf:"bytes,9,rep,name=shifts,proto3" json:"shifts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DailyReportData) Reset() {
	*x = DailyReportData{}
	mi := &file_proto_analytic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyReportData) ProtoMessage() {}

func (x *DailyReportData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyReportData.ProtoReflect.Descriptor instead.
func (*DailyReportData) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{2}
}

func (x *DailyReportData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyReportData) GetTotalEmployees() int32 {
	if x != nil {
		return x.TotalEmployees
	}
	return 0
}

func (x *DailyReportData) GetPresentEmployees() int32 {
	if x != nil {
		return x.PresentEmployees
	}
	return 0
}

func (x *DailyReportData) GetLateEmployees() int32 {
	if x != nil {
		return x.LateEmployees
	}
	return 0
}

func (x *DailyReportData) GetEarlyLeaveEmployees() int32 {
	if x != nil {
		return x.EarlyLeaveEmployees
	}
	return 0
}

func (x *DailyReportData) GetAbsentEmployees() int32 {
	if x != nil {
		return x.AbsentEmployees
	}
	return 0
}

func (x *DailyReportData) GetAttendanceRate() float64 {
	if x != nil {
		return x.AttendanceRate
	}
	return 0
}

func (x *DailyReportData) GetDepartments() []*DepartmentReport {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *DailyReportData) GetShifts() []*ShiftReport {
	if x != nil {
		return x.Shifts
	}
	return nil
}

type DepartmentReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DepartmentName   string                 `protobuf:"bytes,1,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"`
	TotalEmployees   int32                  `protobuf:"varint,2,opt,name=total_employees,json=totalEmployees,proto3" json:"total_employees,omitempty"`
	PresentEmployees int32                  `protobuf:"varint,3,opt,name=present_employees,json=presentEmployees,proto3" json:"present_employees,omitempty"`
	AttendanceRate   float64                `protobuf:"fixed64,4,opt,name=attendance_rate,json=attendanceRate,proto3" json:"attendance_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DepartmentReport) Reset() {
	*x = DepartmentReport{}
	mi := &file_proto_analytic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentReport) ProtoMessage() {}

func (x *DepartmentReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentReport.ProtoReflect.Descriptor instead.
func (*DepartmentReport) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{3}
}

func (x *DepartmentReport) GetDepartmentName() string {
	if x != nil {
		return x.DepartmentName
	}
	return ""
}

func (x *DepartmentReport) GetTotalEmployees() int32 {
	if x != nil {
		return x.TotalEmployees
	}
	return 0
}

func (x *DepartmentReport) GetPresentEmployees() int32 {
	if x != nil {
		return x.PresentEmployees
	}
	return 0
}

func (x *DepartmentReport) GetAttendanceRate() float64 {
	if x != nil {
		return x.AttendanceRate
	}
	return 0
}

type ShiftReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ShiftName        string                 `protobuf:"bytes,1,opt,name=shift_name,json=shiftName,proto3" json:"shift_name,omitempty"`
	StartTime        string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TotalEmployees   int32                  `protobuf:"varint,4,opt,name=total_employees,json=totalEmployees,proto3" json:"total_employees,omitempty"`
	PresentEmployees int32                  `protobuf:"varint,5,opt,name=present_employees,json=presentEmployees,proto3" json:"present_employees,omitempty"`
	AttendanceRate   float64                `protobuf:"fixed64,6,opt,name=attendance_rate,json=attendanceRate,proto3" json:"attendance_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ShiftReport) Reset() {
	*x = ShiftReport{}
	mi := &file_proto_analytic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShiftReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShiftReport) ProtoMessage() {}

func (x *ShiftReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShiftReport.ProtoReflect.Descriptor instead.
func (*ShiftReport) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{4}
}

func (x *ShiftReport) GetShiftName() string {
	if x != nil {
		return x.ShiftName
	}
	return ""
}

func (x *ShiftReport) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ShiftReport) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ShiftReport) GetTotalEmployees() int32 {
	if x != nil {
		return x.TotalEmployees
	}
	return 0
}

func (x *ShiftReport) GetPresentEmployees() int32 {
	if x != nil {
		return x.PresentEmployees
	}
	return 0
}

func (x *ShiftReport) GetAttendanceRate() float64 {
	if x != nil {
		return x.AttendanceRate
	}
	return 0
}

type GetSummaryReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`                          // YYYY-MM
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Required
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryReportRequest) Reset() {
	*x = GetSummaryReportRequest{}
	mi := &file_proto_analytic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryReportRequest) ProtoMessage() {}

func (x *GetSummaryReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryReportRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{5}
}

func (x *GetSummaryReportRequest) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *GetSummaryReportRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *GetSummaryReportRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type GetSummaryReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *SummaryReportData     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryReportResponse) Reset() {
	*x = GetSummaryReportResponse{}
	mi := &file_proto_analytic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryReportResponse) ProtoMessage() {}

func (x *GetSummaryReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryReportResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{6}
}

func (x *GetSummaryReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSummaryReportResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetSummaryReportResponse) GetData() *SummaryReportData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SummaryReportData struct {
	state                  protoimpl.MessageState    `protogen:"open.v1"`
	Month                  string                    `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalWorkingDays       int32                     `protobuf:"varint,2,opt,name=total_working_days,json=totalWorkingDays,proto3" json:"total_working_days,omitempty"`
	TotalEmployees         int32                     `protobuf:"varint,3,opt,name=total_employees,json=totalEmployees,proto3" json:"total_employees,omitempty"`
	AverageAttendanceRate  float64                   `protobuf:"fixed64,4,opt,name=average_attendance_rate,json=averageAttendanceRate,proto3" json:"average_attendance_rate,omitempty"`
	TotalWorkingHours      int32                     `protobuf:"varint,5,opt,name=total_working_hours,json=totalWorkingHours,proto3" json:"total_working_hours,omitempty"`
	TotalOvertimeHours     int32                     `protobuf:"varint,6,opt,name=total_overtime_hours,json=totalOvertimeHours,proto3" json:"total_overtime_hours,omitempty"`
	WeeklySummary          []*WeeklySummary          `protobuf:"bytes,7,rep,name=weekly_summary,json=weeklySummary,proto3" json:"weekly_summary,omitempty"`
	TopAttendanceEmployees []*EmployeeAttendanceStat `protobuf:"bytes,8,rep,name=top_attendance_employees,json=topAttendanceEmployees,proto3" json:"top_attendance_employees,omitempty"`
	LowAttendanceEmployees []*EmployeeAttendanceStat `protobuf:"bytes,9,rep,name=low_attendance_employees,json=lowAttendanceEmployees,proto3" json:"low_attendance_employees,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SummaryReportData) Reset() {
	*x = SummaryReportData{}
	mi := &file_proto_analytic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryReportData) ProtoMessage() {}

func (x *SummaryReportData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryReportData.ProtoReflect.Descriptor instead.
func (*SummaryReportData) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{7}
}

func (x *SummaryReportData) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *SummaryReportData) GetTotalWorkingDays() int32 {
	if x != nil {
		return x.TotalWorkingDays
	}
	return 0
}

func (x *SummaryReportData) GetTotalEmployees() int32 {
	if x != nil {
		return x.TotalEmployees
	}
	return 0
}

func (x *SummaryReportData) GetAverageAttendanceRate() float64 {
	if x != nil {
		return x.AverageAttendanceRate
	}
	return 0
}

func (x *SummaryReportData) GetTotalWorkingHours() int32 {
	if x != nil {
		return x.TotalWorkingHours
	}
	return 0
}

func (x *SummaryReportData) GetTotalOvertimeHours() int32 {
	if x != nil {
		return x.TotalOvertimeHours
	}
	return 0
}

func (x *SummaryReportData) GetWeeklySummary() []*WeeklySummary {
	if x != nil {
		return x.WeeklySummary
	}
	return nil
}

func (x *SummaryReportData) GetTopAttendanceEmployees() []*EmployeeAttendanceStat {
	if x != nil {
		return x.TopAttendanceEmployees
	}
	return nil
}

func (x *SummaryReportData) GetLowAttendanceEmployees() []*EmployeeAttendanceStat {
	if x != nil {
		return x.LowAttendanceEmployees
	}
	return nil
}

type WeeklySummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Week           int32                  `protobuf:"varint,1,opt,name=week,proto3" json:"week,omitempty"`
	StartDate      string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	AttendanceRate float64                `protobuf:"fixed64,4,opt,name=attendance_rate,json=attendanceRate,proto3" json:"attendance_rate,omitempty"`
	TotalHours     int32                  `protobuf:"varint,5,opt,name=total_hours,json=totalHours,proto3" json:"total_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeeklySummary) Reset() {
	*x = WeeklySummary{}
	mi := &file_proto_analytic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklySummary) ProtoMessage() {}

func (x *WeeklySummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklySummary.ProtoReflect.Descriptor instead.
func (*WeeklySummary) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{8}
}

func (x *WeeklySummary) GetWeek() int32 {
	if x != nil {
		return x.Week
	}
	return 0
}

func (x *WeeklySummary) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *WeeklySummary) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *WeeklySummary) GetAttendanceRate() float64 {
	if x != nil {
		return x.AttendanceRate
	}
	return 0
}

func (x *WeeklySummary) GetTotalHours() int32 {
	if x != nil {
		return x.TotalHours
	}
	return 0
}

type EmployeeAttendanceStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmployeeCode   string                 `protobuf:"bytes,1,opt,name=employee_code,json=employeeCode,proto3" json:"employee_code,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PresentDays    int32                  `protobuf:"varint,3,opt,name=present_days,json=presentDays,proto3" json:"present_days,omitempty"`
	AttendanceRate float64                `protobuf:"fixed64,4,opt,name=attendance_rate,json=attendanceRate,proto3" json:"attendance_rate,omitempty"`
	TotalHours     int32                  `protobuf:"varint,5,opt,name=total_hours,json=totalHours,proto3" json:"total_hours,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmployeeAttendanceStat) Reset() {
	*x = EmployeeAttendanceStat{}
	mi := &file_proto_analytic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeAttendanceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeAttendanceStat) ProtoMessage() {}

func (x *EmployeeAttendanceStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeAttendanceStat.ProtoReflect.Descriptor instead.
func (*EmployeeAttendanceStat) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{9}
}

func (x *EmployeeAttendanceStat) GetEmployeeCode() string {
	if x != nil {
		return x.EmployeeCode
	}
	return ""
}

func (x *EmployeeAttendanceStat) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *EmployeeAttendanceStat) GetPresentDays() int32 {
	if x != nil {
		return x.PresentDays
	}
	return 0
}

func (x *EmployeeAttendanceStat) GetAttendanceRate() float64 {
	if x != nil {
		return x.AttendanceRate
	}
	return 0
}

func (x *EmployeeAttendanceStat) GetTotalHours() int32 {
	if x != nil {
		return x.TotalHours
	}
	return 0
}

type ExportReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionInfo   *SessionInfo           `protobuf:"bytes,1,opt,name=session_info,json=sessionInfo,proto3" json:"session_info,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                        // excel, pdf, csv
	CompanyId     string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Required
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`                          // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportRequest) Reset() {
	*x = ExportReportRequest{}
	mi := &file_proto_analytic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportRequest) ProtoMessage() {}

func (x *ExportReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportRequest.ProtoReflect.Descriptor instead.
func (*ExportReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{10}
}

func (x *ExportReportRequest) GetSessionInfo() *SessionInfo {
	if x != nil {
		return x.SessionInfo
	}
	return nil
}

func (x *ExportReportRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ExportReportRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ExportReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportReportRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ExportReportRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ExportReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *ExportReportData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportResponse) Reset() {
	*x = ExportReportResponse{}
	mi := &file_proto_analytic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportResponse) ProtoMessage() {}

func (x *ExportReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportResponse.ProtoReflect.Descriptor instead.
func (*ExportReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{11}
}

func (x *ExportReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ExportReportResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ExportReportResponse) GetData() *ExportReportData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExportReportData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,4,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportReportData) Reset() {
	*x = ExportReportData{}
	mi := &file_proto_analytic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportReportData) ProtoMessage() {}

func (x *ExportReportData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportReportData.ProtoReflect.Descriptor instead.
func (*ExportReportData) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{12}
}

func (x *ExportReportData) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExportReportData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExportReportData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExportReportData) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientAgent   string                 `protobuf:"bytes,5,opt,name=client_agent,json=clientAgent,proto3" json:"client_agent,omitempty"`
	CompanyId     string                 `protobuf:"bytes,6,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"` // Company ID from token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_analytic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_analytic_proto_rawDescGZIP(), []int{13}
}

func (x *SessionInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SessionInfo) GetClientAgent() string {
	if x != nil {
		return x.ClientAgent
	}
	return ""
}

func (x *SessionInfo) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_proto_analytic_proto protoreflect.FileDescriptor

const file_proto_analytic_proto_rawDesc = "" +
	"\n" +
	"\x14proto/analytic.proto\x12\banalytic\"\xa5\x01\n" +
	"\x15GetDailyReportRequest\x128\n" +
	"\fsession_info\x18\x01 \x01(\v2\x15.analytic.SessionInfoR\vsessionInfo\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\"z\n" +
	"\x16GetDailyReportResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.analytic.DailyReportDataR\x04data\"\x97\x03\n" +
	"\x0fDailyReportData\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12'\n" +
	"\x0ftotal_employees\x18\x02 \x01(\x05R\x0etotalEmployees\x12+\n" +
	"\x11present_employees\x18\x03 \x01(\x05R\x10presentEmployees\x12%\n" +
	"\x0elate_employees\x18\x04 \x01(\x05R\rlateEmployees\x122\n" +
	"\x15early_leave_employees\x18\x05 \x01(\x05R\x13earlyLeaveEmployees\x12)\n" +
	"\x10absent_employees\x18\x06 \x01(\x05R\x0fabsentEmployees\x12'\n" +
	"\x0fattendance_rate\x18\a \x01(\x01R\x0eattendanceRate\x12<\n" +
	"\vdepartments\x18\b \x03(\v2\x1a.analytic.DepartmentReportR\vdepartments\x12-\n" +
	"\x06shifts\x18\t \x03(\v2\x15.analytic.ShiftReportR\x06shifts\"\xba\x01\n" +
	"\x10DepartmentReport\x12'\n" +
	"\x0fdepartment_name\x18\x01 \x01(\tR\x0edepartmentName\x12'\n" +
	"\x0ftotal_employees\x18\x02 \x01(\x05R\x0etotalEmployees\x12+\n" +
	"\x11present_employees\x18\x03 \x01(\x05R\x10presentEmployees\x12'\n" +
	"\x0fattendance_rate\x18\x04 \x01(\x01R\x0eattendanceRate\"\xe5\x01\n" +
	"\vShiftReport\x12\x1d\n" +
	"\n" +
	"shift_name\x18\x01 \x01(\tR\tshiftName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12'\n" +
	"\x0ftotal_employees\x18\x04 \x01(\x05R\x0etotalEmployees\x12+\n" +
	"\x11present_employees\x18\x05 \x01(\x05R\x10presentEmployees\x12'\n" +
	"\x0fattendance_rate\x18\x06 \x01(\x01R\x0eattendanceRate\"\x88\x01\n" +
	"\x17GetSummaryReportRequest\x128\n" +
	"\fsession_info\x18\x01 \x01(\v2\x15.analytic.SessionInfoR\vsessionInfo\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\"~\n" +
	"\x18GetSummaryReportResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.analytic.SummaryReportDataR\x04data\"\x92\x04\n" +
	"\x11SummaryReportData\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12,\n" +
	"\x12total_working_days\x18\x02 \x01(\x05R\x10totalWorkingDays\x12'\n" +
	"\x0ftotal_employees\x18\x03 \x01(\x05R\x0etotalEmployees\x126\n" +
	"\x17average_attendance_rate\x18\x04 \x01(\x01R\x15averageAttendanceRate\x12.\n" +
	"\x13total_working_hours\x18\x05 \x01(\x05R\x11totalWorkingHours\x120\n" +
	"\x14total_overtime_hours\x18\x06 \x01(\x05R\x12totalOvertimeHours\x12>\n" +
	"\x0eweekly_summary\x18\a \x03(\v2\x17.analytic.WeeklySummaryR\rweeklySummary\x12Z\n" +
	"\x18top_attendance_employees\x18\b \x03(\v2 .analytic.EmployeeAttendanceStatR\x16topAttendanceEmployees\x12Z\n" +
	"\x18low_attendance_employees\x18\t \x03(\v2 .analytic.EmployeeAttendanceStatR\x16lowAttendanceEmployees\"\xa7\x01\n" +
	"\rWeeklySummary\x12\x12\n" +
	"\x04week\x18\x01 \x01(\x05R\x04week\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12'\n" +
	"\x0fattendance_rate\x18\x04 \x01(\x01R\x0eattendanceRate\x12\x1f\n" +
	"\vtotal_hours\x18\x05 \x01(\x05R\n" +
	"totalHours\"\xc7\x01\n" +
	"\x16EmployeeAttendanceStat\x12#\n" +
	"\remployee_code\x18\x01 \x01(\tR\femployeeCode\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fpresent_days\x18\x03 \x01(\x05R\vpresentDays\x12'\n" +
	"\x0fattendance_rate\x18\x04 \x01(\x01R\x0eattendanceRate\x12\x1f\n" +
	"\vtotal_hours\x18\x05 \x01(\x05R\n" +
	"totalHours\"\xd6\x01\n" +
	"\x13ExportReportRequest\x128\n" +
	"\fsession_info\x18\x01 \x01(\v2\x15.analytic.SessionInfoR\vsessionInfo\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"y\n" +
	"\x14ExportReportResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12.\n" +
	"\x04data\x18\x03 \x01(\v2\x1a.analytic.ExportReportDataR\x04data\"~\n" +
	"\x10ExportReportData\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fdownload_url\x18\x04 \x01(\tR\vdownloadUrl\"\xb8\x01\n" +
	"\vSessionInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12!\n" +
	"\fclient_agent\x18\x05 \x01(\tR\vclientAgent\x12\x1d\n" +
	"\n" +
	"company_id\x18\x06 \x01(\tR\tcompanyId2\x90\x02\n" +
	"\x0fAnalyticService\x12S\n" +
	"\x0eGetDailyReport\x12\x1f.analytic.GetDailyReportRequest\x1a .analytic.GetDailyReportResponse\x12Y\n" +
	"\x10GetSummaryReport\x12!.analytic.GetSummaryReportRequest\x1a\".analytic.GetSummaryReportResponse\x12M\n" +
	"\fExportReport\x12\x1d.analytic.ExportReportRequest\x1a\x1e.analytic.ExportReportResponseBIZGgithub.com/youknow2509/cio_verify_face/server/service_analytic/proto/pbb\x06proto3"

var (
	file_proto_analytic_proto_rawDescOnce sync.Once
	file_proto_analytic_proto_rawDescData []byte
)

func file_proto_analytic_proto_rawDescGZIP() []byte {
	file_proto_analytic_proto_rawDescOnce.Do(func() {
		file_proto_analytic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytic_proto_rawDesc), len(file_proto_analytic_proto_rawDesc)))
	})
	return file_proto_analytic_proto_rawDescData
}

var file_proto_analytic_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_analytic_proto_goTypes = []any{
	(*GetDailyReportRequest)(nil),    // 0: analytic.GetDailyReportRequest
	(*GetDailyReportResponse)(nil),   // 1: analytic.GetDailyReportResponse
	(*DailyReportData)(nil),          // 2: analytic.DailyReportData
	(*DepartmentReport)(nil),         // 3: analytic.DepartmentReport
	(*ShiftReport)(nil),              // 4: analytic.ShiftReport
	(*GetSummaryReportRequest)(nil),  // 5: analytic.GetSummaryReportRequest
	(*GetSummaryReportResponse)(nil), // 6: analytic.GetSummaryReportResponse
	(*SummaryReportData)(nil),        // 7: analytic.SummaryReportData
	(*WeeklySummary)(nil),            // 8: analytic.WeeklySummary
	(*EmployeeAttendanceStat)(nil),   // 9: analytic.EmployeeAttendanceStat
	(*ExportReportRequest)(nil),      // 10: analytic.ExportReportRequest
	(*ExportReportResponse)(nil),     // 11: analytic.ExportReportResponse
	(*ExportReportData)(nil),         // 12: analytic.ExportReportData
	(*SessionInfo)(nil),              // 13: analytic.SessionInfo
}
var file_proto_analytic_proto_depIdxs = []int32{
	13, // 0: analytic.GetDailyReportRequest.session_info:type_name -> analytic.SessionInfo
	2,  // 1: analytic.GetDailyReportResponse.data:type_name -> analytic.DailyReportData
	3,  // 2: analytic.DailyReportData.departments:type_name -> analytic.DepartmentReport
	4,  // 3: analytic.DailyReportData.shifts:type_name -> analytic.ShiftReport
	13, // 4: analytic.GetSummaryReportRequest.session_info:type_name -> analytic.SessionInfo
	7,  // 5: analytic.GetSummaryReportResponse.data:type_name -> analytic.SummaryReportData
	8,  // 6: analytic.SummaryReportData.weekly_summary:type_name -> analytic.WeeklySummary
	9,  // 7: analytic.SummaryReportData.top_attendance_employees:type_name -> analytic.EmployeeAttendanceStat
	9,  // 8: analytic.SummaryReportData.low_attendance_employees:type_name -> analytic.EmployeeAttendanceStat
	13, // 9: analytic.ExportReportRequest.session_info:type_name -> analytic.SessionInfo
	12, // 10: analytic.ExportReportResponse.data:type_name -> analytic.ExportReportData
	0,  // 11: analytic.AnalyticService.GetDailyReport:input_type -> analytic.GetDailyReportRequest
	5,  // 12: analytic.AnalyticService.GetSummaryReport:input_type -> analytic.GetSummaryReportRequest
	10, // 13: analytic.AnalyticService.ExportReport:input_type -> analytic.ExportReportRequest
	1,  // 14: analytic.AnalyticService.GetDailyReport:output_type -> analytic.GetDailyReportResponse
	6,  // 15: analytic.AnalyticService.GetSummaryReport:output_type -> analytic.GetSummaryReportResponse
	11, // 16: analytic.AnalyticService.ExportReport:output_type -> analytic.ExportReportResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_analytic_proto_init() }
func file_proto_analytic_proto_init() {
	if File_proto_analytic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytic_proto_rawDesc), len(file_proto_analytic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytic_proto_goTypes,
		DependencyIndexes: file_proto_analytic_proto_depIdxs,
		MessageInfos:      file_proto_analytic_proto_msgTypes,
	}.Build()
	File_proto_analytic_proto = out.File
	file_proto_analytic_proto_goTypes = nil
	file_proto_analytic_proto_depIdxs = nil
}
