// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v6.33.0
// source: proto/analytic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AnalyticService_GetDailyReport_FullMethodName                  = "/analytic.AnalyticService/GetDailyReport"
	AnalyticService_GetSummaryReport_FullMethodName                = "/analytic.AnalyticService/GetSummaryReport"
	AnalyticService_ExportReport_FullMethodName                    = "/analytic.AnalyticService/ExportReport"
	AnalyticService_GetAttendanceRecords_FullMethodName            = "/analytic.AnalyticService/GetAttendanceRecords"
	AnalyticService_GetAttendanceRecordsByTimeRange_FullMethodName = "/analytic.AnalyticService/GetAttendanceRecordsByTimeRange"
	AnalyticService_GetAttendanceRecordsByEmployee_FullMethodName  = "/analytic.AnalyticService/GetAttendanceRecordsByEmployee"
	AnalyticService_CreateAttendanceRecord_FullMethodName          = "/analytic.AnalyticService/CreateAttendanceRecord"
	AnalyticService_GetDailySummaries_FullMethodName               = "/analytic.AnalyticService/GetDailySummaries"
	AnalyticService_GetDailySummariesByUser_FullMethodName         = "/analytic.AnalyticService/GetDailySummariesByUser"
	AnalyticService_CreateDailySummary_FullMethodName              = "/analytic.AnalyticService/CreateDailySummary"
	AnalyticService_UpdateDailySummary_FullMethodName              = "/analytic.AnalyticService/UpdateDailySummary"
	AnalyticService_GetAuditLogs_FullMethodName                    = "/analytic.AnalyticService/GetAuditLogs"
	AnalyticService_GetAuditLogsByTimeRange_FullMethodName         = "/analytic.AnalyticService/GetAuditLogsByTimeRange"
	AnalyticService_CreateAuditLog_FullMethodName                  = "/analytic.AnalyticService/CreateAuditLog"
	AnalyticService_GetFaceEnrollmentLogs_FullMethodName           = "/analytic.AnalyticService/GetFaceEnrollmentLogs"
	AnalyticService_GetFaceEnrollmentLogsByEmployee_FullMethodName = "/analytic.AnalyticService/GetFaceEnrollmentLogsByEmployee"
	AnalyticService_CreateFaceEnrollmentLog_FullMethodName         = "/analytic.AnalyticService/CreateFaceEnrollmentLog"
)

// AnalyticServiceClient is the client API for AnalyticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics service for inter-service communication
type AnalyticServiceClient interface {
	// ========== Existing Report APIs ==========
	// Get daily attendance report
	GetDailyReport(ctx context.Context, in *GetDailyReportRequest, opts ...grpc.CallOption) (*GetDailyReportResponse, error)
	// Get monthly summary report
	GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error)
	// Export attendance report
	ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
	// ========== Attendance Records APIs ==========
	// Get attendance records for a company (uses: attendance_records table with partition key company_id + year_month)
	GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error)
	// Get attendance records by time range (uses: attendance_records table with clustering key record_time)
	GetAttendanceRecordsByTimeRange(ctx context.Context, in *GetAttendanceRecordsByTimeRangeRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error)
	// Get attendance records for an employee (uses: attendance_records_by_user table with partition key company_id + employee_id + year_month)
	GetAttendanceRecordsByEmployee(ctx context.Context, in *GetAttendanceRecordsByEmployeeRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error)
	// Create attendance record (writes to both attendance_records and attendance_records_by_user for dual indexing)
	CreateAttendanceRecord(ctx context.Context, in *CreateAttendanceRecordRequest, opts ...grpc.CallOption) (*CreateAttendanceRecordResponse, error)
	// ========== Daily Summaries APIs ==========
	// Get daily summaries for a company (uses: daily_summaries table with partition key company_id + summary_month)
	GetDailySummaries(ctx context.Context, in *GetDailySummariesRequest, opts ...grpc.CallOption) (*GetDailySummariesResponse, error)
	// Get daily summaries for a user (uses: daily_summaries_by_user table with partition key company_id + employee_id + summary_month)
	GetDailySummariesByUser(ctx context.Context, in *GetDailySummariesByUserRequest, opts ...grpc.CallOption) (*GetDailySummariesResponse, error)
	// Create daily summary (writes to both daily_summaries and daily_summaries_by_user for dual indexing)
	CreateDailySummary(ctx context.Context, in *CreateDailySummaryRequest, opts ...grpc.CallOption) (*CreateDailySummaryResponse, error)
	// Update daily summary (updates both daily_summaries and daily_summaries_by_user)
	UpdateDailySummary(ctx context.Context, in *UpdateDailySummaryRequest, opts ...grpc.CallOption) (*UpdateDailySummaryResponse, error)
	// ========== Audit Logs APIs ==========
	// Get audit logs for a company (uses: audit_logs table with partition key company_id + year_month)
	GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
	// Get audit logs by time range (uses: audit_logs table with clustering key created_at)
	GetAuditLogsByTimeRange(ctx context.Context, in *GetAuditLogsByTimeRangeRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
	// Create audit log (writes to audit_logs table)
	CreateAuditLog(ctx context.Context, in *CreateAuditLogRequest, opts ...grpc.CallOption) (*CreateAuditLogResponse, error)
	// ========== Face Enrollment Logs APIs ==========
	// Get face enrollment logs for a company (uses: face_enrollment_logs table with partition key company_id + year_month)
	GetFaceEnrollmentLogs(ctx context.Context, in *GetFaceEnrollmentLogsRequest, opts ...grpc.CallOption) (*GetFaceEnrollmentLogsResponse, error)
	// Get face enrollment logs for an employee (uses: face_enrollment_logs table with clustering key employee_id)
	GetFaceEnrollmentLogsByEmployee(ctx context.Context, in *GetFaceEnrollmentLogsByEmployeeRequest, opts ...grpc.CallOption) (*GetFaceEnrollmentLogsResponse, error)
	// Create face enrollment log (writes to face_enrollment_logs table)
	CreateFaceEnrollmentLog(ctx context.Context, in *CreateFaceEnrollmentLogRequest, opts ...grpc.CallOption) (*CreateFaceEnrollmentLogResponse, error)
}

type analyticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticServiceClient(cc grpc.ClientConnInterface) AnalyticServiceClient {
	return &analyticServiceClient{cc}
}

func (c *analyticServiceClient) GetDailyReport(ctx context.Context, in *GetDailyReportRequest, opts ...grpc.CallOption) (*GetDailyReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetSummaryReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_ExportReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetAttendanceRecords(ctx context.Context, in *GetAttendanceRecordsRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAttendanceRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetAttendanceRecordsByTimeRange(ctx context.Context, in *GetAttendanceRecordsByTimeRangeRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAttendanceRecordsByTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetAttendanceRecordsByEmployee(ctx context.Context, in *GetAttendanceRecordsByEmployeeRequest, opts ...grpc.CallOption) (*GetAttendanceRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttendanceRecordsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAttendanceRecordsByEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) CreateAttendanceRecord(ctx context.Context, in *CreateAttendanceRecordRequest, opts ...grpc.CallOption) (*CreateAttendanceRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAttendanceRecordResponse)
	err := c.cc.Invoke(ctx, AnalyticService_CreateAttendanceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetDailySummaries(ctx context.Context, in *GetDailySummariesRequest, opts ...grpc.CallOption) (*GetDailySummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailySummariesResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetDailySummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetDailySummariesByUser(ctx context.Context, in *GetDailySummariesByUserRequest, opts ...grpc.CallOption) (*GetDailySummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailySummariesResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetDailySummariesByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) CreateDailySummary(ctx context.Context, in *CreateDailySummaryRequest, opts ...grpc.CallOption) (*CreateDailySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDailySummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticService_CreateDailySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) UpdateDailySummary(ctx context.Context, in *UpdateDailySummaryRequest, opts ...grpc.CallOption) (*UpdateDailySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDailySummaryResponse)
	err := c.cc.Invoke(ctx, AnalyticService_UpdateDailySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetAuditLogsByTimeRange(ctx context.Context, in *GetAuditLogsByTimeRangeRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetAuditLogsByTimeRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) CreateAuditLog(ctx context.Context, in *CreateAuditLogRequest, opts ...grpc.CallOption) (*CreateAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAuditLogResponse)
	err := c.cc.Invoke(ctx, AnalyticService_CreateAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetFaceEnrollmentLogs(ctx context.Context, in *GetFaceEnrollmentLogsRequest, opts ...grpc.CallOption) (*GetFaceEnrollmentLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFaceEnrollmentLogsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetFaceEnrollmentLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetFaceEnrollmentLogsByEmployee(ctx context.Context, in *GetFaceEnrollmentLogsByEmployeeRequest, opts ...grpc.CallOption) (*GetFaceEnrollmentLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFaceEnrollmentLogsResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetFaceEnrollmentLogsByEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) CreateFaceEnrollmentLog(ctx context.Context, in *CreateFaceEnrollmentLogRequest, opts ...grpc.CallOption) (*CreateFaceEnrollmentLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFaceEnrollmentLogResponse)
	err := c.cc.Invoke(ctx, AnalyticService_CreateFaceEnrollmentLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticServiceServer is the server API for AnalyticService service.
// All implementations must embed UnimplementedAnalyticServiceServer
// for forward compatibility
//
// Analytics service for inter-service communication
type AnalyticServiceServer interface {
	// ========== Existing Report APIs ==========
	// Get daily attendance report
	GetDailyReport(context.Context, *GetDailyReportRequest) (*GetDailyReportResponse, error)
	// Get monthly summary report
	GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error)
	// Export attendance report
	ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error)
	// ========== Attendance Records APIs ==========
	// Get attendance records for a company (uses: attendance_records table with partition key company_id + year_month)
	GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*GetAttendanceRecordsResponse, error)
	// Get attendance records by time range (uses: attendance_records table with clustering key record_time)
	GetAttendanceRecordsByTimeRange(context.Context, *GetAttendanceRecordsByTimeRangeRequest) (*GetAttendanceRecordsResponse, error)
	// Get attendance records for an employee (uses: attendance_records_by_user table with partition key company_id + employee_id + year_month)
	GetAttendanceRecordsByEmployee(context.Context, *GetAttendanceRecordsByEmployeeRequest) (*GetAttendanceRecordsResponse, error)
	// Create attendance record (writes to both attendance_records and attendance_records_by_user for dual indexing)
	CreateAttendanceRecord(context.Context, *CreateAttendanceRecordRequest) (*CreateAttendanceRecordResponse, error)
	// ========== Daily Summaries APIs ==========
	// Get daily summaries for a company (uses: daily_summaries table with partition key company_id + summary_month)
	GetDailySummaries(context.Context, *GetDailySummariesRequest) (*GetDailySummariesResponse, error)
	// Get daily summaries for a user (uses: daily_summaries_by_user table with partition key company_id + employee_id + summary_month)
	GetDailySummariesByUser(context.Context, *GetDailySummariesByUserRequest) (*GetDailySummariesResponse, error)
	// Create daily summary (writes to both daily_summaries and daily_summaries_by_user for dual indexing)
	CreateDailySummary(context.Context, *CreateDailySummaryRequest) (*CreateDailySummaryResponse, error)
	// Update daily summary (updates both daily_summaries and daily_summaries_by_user)
	UpdateDailySummary(context.Context, *UpdateDailySummaryRequest) (*UpdateDailySummaryResponse, error)
	// ========== Audit Logs APIs ==========
	// Get audit logs for a company (uses: audit_logs table with partition key company_id + year_month)
	GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error)
	// Get audit logs by time range (uses: audit_logs table with clustering key created_at)
	GetAuditLogsByTimeRange(context.Context, *GetAuditLogsByTimeRangeRequest) (*GetAuditLogsResponse, error)
	// Create audit log (writes to audit_logs table)
	CreateAuditLog(context.Context, *CreateAuditLogRequest) (*CreateAuditLogResponse, error)
	// ========== Face Enrollment Logs APIs ==========
	// Get face enrollment logs for a company (uses: face_enrollment_logs table with partition key company_id + year_month)
	GetFaceEnrollmentLogs(context.Context, *GetFaceEnrollmentLogsRequest) (*GetFaceEnrollmentLogsResponse, error)
	// Get face enrollment logs for an employee (uses: face_enrollment_logs table with clustering key employee_id)
	GetFaceEnrollmentLogsByEmployee(context.Context, *GetFaceEnrollmentLogsByEmployeeRequest) (*GetFaceEnrollmentLogsResponse, error)
	// Create face enrollment log (writes to face_enrollment_logs table)
	CreateFaceEnrollmentLog(context.Context, *CreateFaceEnrollmentLogRequest) (*CreateFaceEnrollmentLogResponse, error)
	mustEmbedUnimplementedAnalyticServiceServer()
}

// UnimplementedAnalyticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticServiceServer struct {
}

func (UnimplementedAnalyticServiceServer) GetDailyReport(context.Context, *GetDailyReportRequest) (*GetDailyReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyReport not implemented")
}
func (UnimplementedAnalyticServiceServer) GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummaryReport not implemented")
}
func (UnimplementedAnalyticServiceServer) ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportReport not implemented")
}
func (UnimplementedAnalyticServiceServer) GetAttendanceRecords(context.Context, *GetAttendanceRecordsRequest) (*GetAttendanceRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecords not implemented")
}
func (UnimplementedAnalyticServiceServer) GetAttendanceRecordsByTimeRange(context.Context, *GetAttendanceRecordsByTimeRangeRequest) (*GetAttendanceRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecordsByTimeRange not implemented")
}
func (UnimplementedAnalyticServiceServer) GetAttendanceRecordsByEmployee(context.Context, *GetAttendanceRecordsByEmployeeRequest) (*GetAttendanceRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttendanceRecordsByEmployee not implemented")
}
func (UnimplementedAnalyticServiceServer) CreateAttendanceRecord(context.Context, *CreateAttendanceRecordRequest) (*CreateAttendanceRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAttendanceRecord not implemented")
}
func (UnimplementedAnalyticServiceServer) GetDailySummaries(context.Context, *GetDailySummariesRequest) (*GetDailySummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailySummaries not implemented")
}
func (UnimplementedAnalyticServiceServer) GetDailySummariesByUser(context.Context, *GetDailySummariesByUserRequest) (*GetDailySummariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailySummariesByUser not implemented")
}
func (UnimplementedAnalyticServiceServer) CreateDailySummary(context.Context, *CreateDailySummaryRequest) (*CreateDailySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDailySummary not implemented")
}
func (UnimplementedAnalyticServiceServer) UpdateDailySummary(context.Context, *UpdateDailySummaryRequest) (*UpdateDailySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDailySummary not implemented")
}
func (UnimplementedAnalyticServiceServer) GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedAnalyticServiceServer) GetAuditLogsByTimeRange(context.Context, *GetAuditLogsByTimeRangeRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuditLogsByTimeRange not implemented")
}
func (UnimplementedAnalyticServiceServer) CreateAuditLog(context.Context, *CreateAuditLogRequest) (*CreateAuditLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAuditLog not implemented")
}
func (UnimplementedAnalyticServiceServer) GetFaceEnrollmentLogs(context.Context, *GetFaceEnrollmentLogsRequest) (*GetFaceEnrollmentLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFaceEnrollmentLogs not implemented")
}
func (UnimplementedAnalyticServiceServer) GetFaceEnrollmentLogsByEmployee(context.Context, *GetFaceEnrollmentLogsByEmployeeRequest) (*GetFaceEnrollmentLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFaceEnrollmentLogsByEmployee not implemented")
}
func (UnimplementedAnalyticServiceServer) CreateFaceEnrollmentLog(context.Context, *CreateFaceEnrollmentLogRequest) (*CreateFaceEnrollmentLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFaceEnrollmentLog not implemented")
}
func (UnimplementedAnalyticServiceServer) mustEmbedUnimplementedAnalyticServiceServer() {}

// UnsafeAnalyticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticServiceServer will
// result in compilation errors.
type UnsafeAnalyticServiceServer interface {
	mustEmbedUnimplementedAnalyticServiceServer()
}

func RegisterAnalyticServiceServer(s grpc.ServiceRegistrar, srv AnalyticServiceServer) {
	s.RegisterService(&AnalyticService_ServiceDesc, srv)
}

func _AnalyticService_GetDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetDailyReport(ctx, req.(*GetDailyReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetSummaryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetSummaryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetSummaryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetSummaryReport(ctx, req.(*GetSummaryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_ExportReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).ExportReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_ExportReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).ExportReport(ctx, req.(*ExportReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetAttendanceRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAttendanceRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAttendanceRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAttendanceRecords(ctx, req.(*GetAttendanceRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetAttendanceRecordsByTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsByTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAttendanceRecordsByTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAttendanceRecordsByTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAttendanceRecordsByTimeRange(ctx, req.(*GetAttendanceRecordsByTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetAttendanceRecordsByEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttendanceRecordsByEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAttendanceRecordsByEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAttendanceRecordsByEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAttendanceRecordsByEmployee(ctx, req.(*GetAttendanceRecordsByEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_CreateAttendanceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAttendanceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).CreateAttendanceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_CreateAttendanceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).CreateAttendanceRecord(ctx, req.(*CreateAttendanceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetDailySummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailySummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetDailySummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetDailySummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetDailySummaries(ctx, req.(*GetDailySummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetDailySummariesByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailySummariesByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetDailySummariesByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetDailySummariesByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetDailySummariesByUser(ctx, req.(*GetDailySummariesByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_CreateDailySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDailySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).CreateDailySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_CreateDailySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).CreateDailySummary(ctx, req.(*CreateDailySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_UpdateDailySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDailySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).UpdateDailySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_UpdateDailySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).UpdateDailySummary(ctx, req.(*UpdateDailySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAuditLogs(ctx, req.(*GetAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetAuditLogsByTimeRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogsByTimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetAuditLogsByTimeRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetAuditLogsByTimeRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetAuditLogsByTimeRange(ctx, req.(*GetAuditLogsByTimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_CreateAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).CreateAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_CreateAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).CreateAuditLog(ctx, req.(*CreateAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetFaceEnrollmentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFaceEnrollmentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetFaceEnrollmentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetFaceEnrollmentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetFaceEnrollmentLogs(ctx, req.(*GetFaceEnrollmentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetFaceEnrollmentLogsByEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFaceEnrollmentLogsByEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetFaceEnrollmentLogsByEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetFaceEnrollmentLogsByEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetFaceEnrollmentLogsByEmployee(ctx, req.(*GetFaceEnrollmentLogsByEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_CreateFaceEnrollmentLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFaceEnrollmentLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).CreateFaceEnrollmentLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_CreateFaceEnrollmentLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).CreateFaceEnrollmentLog(ctx, req.(*CreateFaceEnrollmentLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticService_ServiceDesc is the grpc.ServiceDesc for AnalyticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytic.AnalyticService",
	HandlerType: (*AnalyticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyReport",
			Handler:    _AnalyticService_GetDailyReport_Handler,
		},
		{
			MethodName: "GetSummaryReport",
			Handler:    _AnalyticService_GetSummaryReport_Handler,
		},
		{
			MethodName: "ExportReport",
			Handler:    _AnalyticService_ExportReport_Handler,
		},
		{
			MethodName: "GetAttendanceRecords",
			Handler:    _AnalyticService_GetAttendanceRecords_Handler,
		},
		{
			MethodName: "GetAttendanceRecordsByTimeRange",
			Handler:    _AnalyticService_GetAttendanceRecordsByTimeRange_Handler,
		},
		{
			MethodName: "GetAttendanceRecordsByEmployee",
			Handler:    _AnalyticService_GetAttendanceRecordsByEmployee_Handler,
		},
		{
			MethodName: "CreateAttendanceRecord",
			Handler:    _AnalyticService_CreateAttendanceRecord_Handler,
		},
		{
			MethodName: "GetDailySummaries",
			Handler:    _AnalyticService_GetDailySummaries_Handler,
		},
		{
			MethodName: "GetDailySummariesByUser",
			Handler:    _AnalyticService_GetDailySummariesByUser_Handler,
		},
		{
			MethodName: "CreateDailySummary",
			Handler:    _AnalyticService_CreateDailySummary_Handler,
		},
		{
			MethodName: "UpdateDailySummary",
			Handler:    _AnalyticService_UpdateDailySummary_Handler,
		},
		{
			MethodName: "GetAuditLogs",
			Handler:    _AnalyticService_GetAuditLogs_Handler,
		},
		{
			MethodName: "GetAuditLogsByTimeRange",
			Handler:    _AnalyticService_GetAuditLogsByTimeRange_Handler,
		},
		{
			MethodName: "CreateAuditLog",
			Handler:    _AnalyticService_CreateAuditLog_Handler,
		},
		{
			MethodName: "GetFaceEnrollmentLogs",
			Handler:    _AnalyticService_GetFaceEnrollmentLogs_Handler,
		},
		{
			MethodName: "GetFaceEnrollmentLogsByEmployee",
			Handler:    _AnalyticService_GetFaceEnrollmentLogsByEmployee_Handler,
		},
		{
			MethodName: "CreateFaceEnrollmentLog",
			Handler:    _AnalyticService_CreateFaceEnrollmentLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytic.proto",
}
