// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/analytic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticService_GetDailyReport_FullMethodName   = "/analytic.AnalyticService/GetDailyReport"
	AnalyticService_GetSummaryReport_FullMethodName = "/analytic.AnalyticService/GetSummaryReport"
	AnalyticService_ExportReport_FullMethodName     = "/analytic.AnalyticService/ExportReport"
)

// AnalyticServiceClient is the client API for AnalyticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Analytics service for inter-service communication
type AnalyticServiceClient interface {
	// Get daily attendance report
	GetDailyReport(ctx context.Context, in *GetDailyReportRequest, opts ...grpc.CallOption) (*GetDailyReportResponse, error)
	// Get monthly summary report
	GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error)
	// Export attendance report
	ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error)
}

type analyticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticServiceClient(cc grpc.ClientConnInterface) AnalyticServiceClient {
	return &analyticServiceClient{cc}
}

func (c *analyticServiceClient) GetDailyReport(ctx context.Context, in *GetDailyReportRequest, opts ...grpc.CallOption) (*GetDailyReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetDailyReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) GetSummaryReport(ctx context.Context, in *GetSummaryReportRequest, opts ...grpc.CallOption) (*GetSummaryReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSummaryReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_GetSummaryReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticServiceClient) ExportReport(ctx context.Context, in *ExportReportRequest, opts ...grpc.CallOption) (*ExportReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportReportResponse)
	err := c.cc.Invoke(ctx, AnalyticService_ExportReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticServiceServer is the server API for AnalyticService service.
// All implementations must embed UnimplementedAnalyticServiceServer
// for forward compatibility.
//
// Analytics service for inter-service communication
type AnalyticServiceServer interface {
	// Get daily attendance report
	GetDailyReport(context.Context, *GetDailyReportRequest) (*GetDailyReportResponse, error)
	// Get monthly summary report
	GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error)
	// Export attendance report
	ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error)
	mustEmbedUnimplementedAnalyticServiceServer()
}

// UnimplementedAnalyticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticServiceServer struct{}

func (UnimplementedAnalyticServiceServer) GetDailyReport(context.Context, *GetDailyReportRequest) (*GetDailyReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyReport not implemented")
}
func (UnimplementedAnalyticServiceServer) GetSummaryReport(context.Context, *GetSummaryReportRequest) (*GetSummaryReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSummaryReport not implemented")
}
func (UnimplementedAnalyticServiceServer) ExportReport(context.Context, *ExportReportRequest) (*ExportReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportReport not implemented")
}
func (UnimplementedAnalyticServiceServer) mustEmbedUnimplementedAnalyticServiceServer() {}
func (UnimplementedAnalyticServiceServer) testEmbeddedByValue()                         {}

// UnsafeAnalyticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticServiceServer will
// result in compilation errors.
type UnsafeAnalyticServiceServer interface {
	mustEmbedUnimplementedAnalyticServiceServer()
}

func RegisterAnalyticServiceServer(s grpc.ServiceRegistrar, srv AnalyticServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticService_ServiceDesc, srv)
}

func _AnalyticService_GetDailyReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetDailyReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetDailyReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetDailyReport(ctx, req.(*GetDailyReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_GetSummaryReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).GetSummaryReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_GetSummaryReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).GetSummaryReport(ctx, req.(*GetSummaryReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticService_ExportReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticServiceServer).ExportReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticService_ExportReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticServiceServer).ExportReport(ctx, req.(*ExportReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticService_ServiceDesc is the grpc.ServiceDesc for AnalyticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytic.AnalyticService",
	HandlerType: (*AnalyticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDailyReport",
			Handler:    _AnalyticService_GetDailyReport_Handler,
		},
		{
			MethodName: "GetSummaryReport",
			Handler:    _AnalyticService_GetSummaryReport_Handler,
		},
		{
			MethodName: "ExportReport",
			Handler:    _AnalyticService_ExportReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytic.proto",
}
