// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/Youknow2509/",
            "email": "lytranvinh.work@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/attendance": {
            "post": {
                "description": "Add attendance record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Add attendance record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body add attendance record",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddAttendanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/records": {
            "post": {
                "description": "Get attendance records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get attendance records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body get attendance records",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetAttendanceRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/records/employee": {
            "post": {
                "description": "Get attendance records for employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get attendance records for employee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body get attendance records for employee",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetAttendanceRecordsEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/records/employee/summary/daily": {
            "post": {
                "description": "Get daily attendance summary for employee",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get daily attendance summary for employee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body get daily attendance summary for employee",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetDailyAttendanceSummaryEmployeeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/records/summary/daily": {
            "post": {
                "description": "Get daily attendance summary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get daily attendance summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "With the bearer started",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body get daily attendance summary",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetDailyAttendanceSummaryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddAttendanceRequest": {
            "type": "object",
            "required": [
                "company_id",
                "device_id",
                "employee_id",
                "face_image_url",
                "location_coordinates",
                "record_time",
                "verification_method",
                "verification_score"
            ],
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "face_image_url": {
                    "type": "string"
                },
                "location_coordinates": {
                    "type": "string"
                },
                "record_time": {
                    "type": "integer"
                },
                "verification_method": {
                    "type": "string"
                },
                "verification_score": {
                    "type": "number",
                    "maximum": 1,
                    "minimum": 0
                }
            }
        },
        "dto.ErrResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Ma status code",
                    "type": "integer"
                },
                "detail": {
                    "description": "Thong bao loi"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.GetAttendanceRecordsEmployeeRequest": {
            "type": "object",
            "required": [
                "company_id",
                "year_month"
            ],
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "page_size": {
                    "type": "integer"
                },
                "page_stage": {
                    "type": "string"
                },
                "year_month": {
                    "description": "Format: YYYY-MM",
                    "type": "string"
                }
            }
        },
        "dto.GetAttendanceRecordsRequest": {
            "type": "object",
            "required": [
                "company_id",
                "year_month"
            ],
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "page_size": {
                    "type": "integer"
                },
                "page_stage": {
                    "type": "string"
                },
                "year_month": {
                    "description": "Format: YYYY-MM",
                    "type": "string"
                }
            }
        },
        "dto.GetDailyAttendanceSummaryEmployeeRequest": {
            "type": "object",
            "required": [
                "company_id"
            ],
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "employee_id": {
                    "type": "string"
                },
                "page_size": {
                    "type": "integer"
                },
                "page_stage": {
                    "type": "string"
                },
                "summary_month": {
                    "description": "Format: YYYY-MM",
                    "type": "string"
                }
            }
        },
        "dto.GetDailyAttendanceSummaryRequest": {
            "type": "object",
            "required": [
                "company_id"
            ],
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "page_size": {
                    "type": "integer"
                },
                "page_stage": {
                    "type": "string"
                },
                "summary_month": {
                    "description": "Format: YYYY-MM",
                    "type": "string"
                },
                "work_date": {
                    "description": "Unix timestamp in milliseconds",
                    "type": "integer"
                }
            }
        },
        "dto.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Ma status code",
                    "type": "integer"
                },
                "data": {
                    "description": "Du lieu duoc return"
                },
                "message": {
                    "description": "Thong bao loi",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Swagger Chat Service Auth REST API",
	Description:      "This is a REST API for the Chat Service Auth.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
