// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/Youknow2509/",
            "email": "lytranvinh.work@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/attendance/check_in": {
            "post": {
                "description": "User check-in for attendance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Check In attendance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body check-in",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CheckInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/check_out": {
            "post": {
                "description": "User check-out for attendance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Check Out attendance",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body check-out",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CheckOutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/history/my": {
            "post": {
                "description": "Retrieve the attendance history for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get My Attendance History",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body to get my attendance records",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetMyAttendanceRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        },
        "/v1/attendance/records": {
            "post": {
                "description": "Retrieve attendance records for device, day, user, ...",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attendance"
                ],
                "summary": "Get Attendance Records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Request body to get attendance records",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GetAttendanceRecordsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ResponseData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CheckInRequest": {
            "type": "object",
            "required": [
                "device_id",
                "face_image_url",
                "location",
                "timestamp",
                "user_id",
                "verification_method",
                "verification_score"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "face_image_url": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "verification_method": {
                    "type": "string"
                },
                "verification_score": {
                    "type": "number"
                }
            }
        },
        "dto.CheckOutRequest": {
            "type": "object",
            "required": [
                "device_id",
                "face_image_url",
                "location",
                "timestamp",
                "user_id",
                "verification_method",
                "verification_score"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "face_image_url": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "verification_method": {
                    "type": "string"
                },
                "verification_score": {
                    "type": "number"
                }
            }
        },
        "dto.ErrResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Ma status code",
                    "type": "integer"
                },
                "detail": {
                    "description": "Thong bao loi"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "dto.GetAttendanceRecordsRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_size": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "dto.GetMyAttendanceRecordsRequest": {
            "type": "object",
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "page": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_size": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 1
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "dto.ResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Ma status code",
                    "type": "integer"
                },
                "data": {
                    "description": "Du lieu duoc return"
                },
                "message": {
                    "description": "Thong bao loi",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Swagger Chat Service Auth REST API",
	Description:      "This is a REST API for the Chat Service Auth.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
