// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.2
// source: proto/auth.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages for ValidateToken
type ValidateTokenRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Token              string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequiredPermission *string                `protobuf:"bytes,2,opt,name=required_permission,json=requiredPermission,proto3,oneof" json:"required_permission,omitempty"`
	CompanyId          *string                `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3,oneof" json:"company_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateTokenRequest) GetRequiredPermission() string {
	if x != nil && x.RequiredPermission != nil {
		return *x.RequiredPermission
	}
	return ""
}

func (x *ValidateTokenRequest) GetCompanyId() string {
	if x != nil && x.CompanyId != nil {
		return *x.CompanyId
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ValidateTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidateTokenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidateTokenResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ValidateTokenResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// Messages for GetUserInfo
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CompanyId     string                 `protobuf:"bytes,5,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetUserInfoResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetUserInfoResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetUserInfoResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GetUserInfoResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetUserInfoResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetUserInfoResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GetUserInfoResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Messages for CheckUserPermission
type CheckUserPermissionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId          string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	RequiredPermission *string                `protobuf:"bytes,3,opt,name=required_permission,json=requiredPermission,proto3,oneof" json:"required_permission,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckUserPermissionRequest) Reset() {
	*x = CheckUserPermissionRequest{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionRequest) ProtoMessage() {}

func (x *CheckUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CheckUserPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserPermissionRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CheckUserPermissionRequest) GetRequiredPermission() string {
	if x != nil && x.RequiredPermission != nil {
		return *x.RequiredPermission
	}
	return ""
}

type CheckUserPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	UserRole      string                 `protobuf:"bytes,2,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPermissionResponse) Reset() {
	*x = CheckUserPermissionResponse{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionResponse) ProtoMessage() {}

func (x *CheckUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUserPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

func (x *CheckUserPermissionResponse) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *CheckUserPermissionResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CheckUserPermissionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Messages for CheckDeviceInCompany
type CheckDeviceInCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDeviceInCompanyRequest) Reset() {
	*x = CheckDeviceInCompanyRequest{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDeviceInCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeviceInCompanyRequest) ProtoMessage() {}

func (x *CheckDeviceInCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeviceInCompanyRequest.ProtoReflect.Descriptor instead.
func (*CheckDeviceInCompanyRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *CheckDeviceInCompanyRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CheckDeviceInCompanyRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type CheckDeviceInCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceExists  bool                   `protobuf:"varint,1,opt,name=device_exists,json=deviceExists,proto3" json:"device_exists,omitempty"`
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	DeviceName    string                 `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceType    string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDeviceInCompanyResponse) Reset() {
	*x = CheckDeviceInCompanyResponse{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDeviceInCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDeviceInCompanyResponse) ProtoMessage() {}

func (x *CheckDeviceInCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDeviceInCompanyResponse.ProtoReflect.Descriptor instead.
func (*CheckDeviceInCompanyResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CheckDeviceInCompanyResponse) GetDeviceExists() bool {
	if x != nil {
		return x.DeviceExists
	}
	return false
}

func (x *CheckDeviceInCompanyResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CheckDeviceInCompanyResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *CheckDeviceInCompanyResponse) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *CheckDeviceInCompanyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Messages for ValidateDeviceSession
type ValidateDeviceSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDeviceSessionRequest) Reset() {
	*x = ValidateDeviceSessionRequest{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeviceSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeviceSessionRequest) ProtoMessage() {}

func (x *ValidateDeviceSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeviceSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateDeviceSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateDeviceSessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ValidateDeviceSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *ValidateDeviceSessionRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type ValidateDeviceSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateDeviceSessionResponse) Reset() {
	*x = ValidateDeviceSessionResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateDeviceSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateDeviceSessionResponse) ProtoMessage() {}

func (x *ValidateDeviceSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateDeviceSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateDeviceSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateDeviceSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateDeviceSessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ValidateDeviceSessionResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ValidateDeviceSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateDeviceSessionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ValidateDeviceSessionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Messages for GetUserCompany
type GetUserCompanyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCompanyRequest) Reset() {
	*x = GetUserCompanyRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCompanyRequest) ProtoMessage() {}

func (x *GetUserCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetUserCompanyRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserCompanyRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserCompanyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	CompanyName   string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	CompanyCode   string                 `protobuf:"bytes,3,opt,name=company_code,json=companyCode,proto3" json:"company_code,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	UserRole      string                 `protobuf:"bytes,5,opt,name=user_role,json=userRole,proto3" json:"user_role,omitempty"`
	Permissions   []string               `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCompanyResponse) Reset() {
	*x = GetUserCompanyResponse{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCompanyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCompanyResponse) ProtoMessage() {}

func (x *GetUserCompanyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCompanyResponse.ProtoReflect.Descriptor instead.
func (*GetUserCompanyResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserCompanyResponse) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetUserCompanyResponse) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetUserCompanyResponse) GetCompanyCode() string {
	if x != nil {
		return x.CompanyCode
	}
	return ""
}

func (x *GetUserCompanyResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetUserCompanyResponse) GetUserRole() string {
	if x != nil {
		return x.UserRole
	}
	return ""
}

func (x *GetUserCompanyResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetUserCompanyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Messages for BatchValidateTokens
type TokenValidation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // To match request with response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidation) Reset() {
	*x = TokenValidation{}
	mi := &file_proto_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidation) ProtoMessage() {}

func (x *TokenValidation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidation.ProtoReflect.Descriptor instead.
func (*TokenValidation) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{12}
}

func (x *TokenValidation) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenValidation) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BatchValidateTokensRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tokens             []*TokenValidation     `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	RequiredPermission *string                `protobuf:"bytes,2,opt,name=required_permission,json=requiredPermission,proto3,oneof" json:"required_permission,omitempty"`
	CompanyId          *string                `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3,oneof" json:"company_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BatchValidateTokensRequest) Reset() {
	*x = BatchValidateTokensRequest{}
	mi := &file_proto_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateTokensRequest) ProtoMessage() {}

func (x *BatchValidateTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateTokensRequest.ProtoReflect.Descriptor instead.
func (*BatchValidateTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{13}
}

func (x *BatchValidateTokensRequest) GetTokens() []*TokenValidation {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *BatchValidateTokensRequest) GetRequiredPermission() string {
	if x != nil && x.RequiredPermission != nil {
		return *x.RequiredPermission
	}
	return ""
}

func (x *BatchValidateTokensRequest) GetCompanyId() string {
	if x != nil && x.CompanyId != nil {
		return *x.CompanyId
	}
	return ""
}

type TokenValidationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Permissions   []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenValidationResult) Reset() {
	*x = TokenValidationResult{}
	mi := &file_proto_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenValidationResult) ProtoMessage() {}

func (x *TokenValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenValidationResult.ProtoReflect.Descriptor instead.
func (*TokenValidationResult) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{14}
}

func (x *TokenValidationResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TokenValidationResult) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *TokenValidationResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenValidationResult) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *TokenValidationResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenValidationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TokenValidationResult) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenValidationResult) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type BatchValidateTokensResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Results       []*TokenValidationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchValidateTokensResponse) Reset() {
	*x = BatchValidateTokensResponse{}
	mi := &file_proto_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateTokensResponse) ProtoMessage() {}

func (x *BatchValidateTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateTokensResponse.ProtoReflect.Descriptor instead.
func (*BatchValidateTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{15}
}

func (x *BatchValidateTokensResponse) GetResults() []*TokenValidationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\"\xad\x01\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x124\n" +
	"\x13required_permission\x18\x02 \x01(\tH\x00R\x12requiredPermission\x88\x01\x01\x12\"\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tH\x01R\tcompanyId\x88\x01\x01B\x16\n" +
	"\x14_required_permissionB\r\n" +
	"\v_company_id\"\xea\x01\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\"-\n" +
	"\x12GetUserInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb3\x02\n" +
	"\x13GetUserInfoResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"company_id\x18\x05 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"\xa2\x01\n" +
	"\x1aCheckUserPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x124\n" +
	"\x13required_permission\x18\x03 \x01(\tH\x00R\x12requiredPermission\x88\x01\x01B\x16\n" +
	"\x14_required_permission\"\xa8\x01\n" +
	"\x1bCheckUserPermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\x12\x1b\n" +
	"\tuser_role\x18\x02 \x01(\tR\buserRole\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"Y\n" +
	"\x1bCheckDeviceInCompanyRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"\xc7\x01\n" +
	"\x1cCheckDeviceInCompanyResponse\x12#\n" +
	"\rdevice_exists\x18\x01 \x01(\bR\fdeviceExists\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\x7f\n" +
	"\x1cValidateDeviceSessionRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\"\xce\x01\n" +
	"\x1dValidateDeviceSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"0\n" +
	"\x15GetUserCompanyRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xfe\x01\n" +
	"\x16GetUserCompanyResponse\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12!\n" +
	"\fcompany_name\x18\x02 \x01(\tR\vcompanyName\x12!\n" +
	"\fcompany_code\x18\x03 \x01(\tR\vcompanyCode\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1b\n" +
	"\tuser_role\x18\x05 \x01(\tR\buserRole\x12 \n" +
	"\vpermissions\x18\x06 \x03(\tR\vpermissions\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\"F\n" +
	"\x0fTokenValidation\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xcc\x01\n" +
	"\x1aBatchValidateTokensRequest\x12-\n" +
	"\x06tokens\x18\x01 \x03(\v2\x15.auth.TokenValidationR\x06tokens\x124\n" +
	"\x13required_permission\x18\x02 \x01(\tH\x00R\x12requiredPermission\x88\x01\x01\x12\"\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tH\x01R\tcompanyId\x88\x01\x01B\x16\n" +
	"\x14_required_permissionB\r\n" +
	"\v_company_id\"\x89\x02\n" +
	"\x15TokenValidationResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x04 \x01(\tR\tcompanyId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\"T\n" +
	"\x1bBatchValidateTokensResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.auth.TokenValidationResultR\aresults2\xe1\x04\n" +
	"\vAuthService\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12B\n" +
	"\vGetUserInfo\x12\x18.auth.GetUserInfoRequest\x1a\x19.auth.GetUserInfoResponse\x12Z\n" +
	"\x13CheckUserPermission\x12 .auth.CheckUserPermissionRequest\x1a!.auth.CheckUserPermissionResponse\x12]\n" +
	"\x14CheckDeviceInCompany\x12!.auth.CheckDeviceInCompanyRequest\x1a\".auth.CheckDeviceInCompanyResponse\x12`\n" +
	"\x15ValidateDeviceSession\x12\".auth.ValidateDeviceSessionRequest\x1a#.auth.ValidateDeviceSessionResponse\x12K\n" +
	"\x0eGetUserCompany\x12\x1b.auth.GetUserCompanyRequest\x1a\x1c.auth.GetUserCompanyResponse\x12Z\n" +
	"\x13BatchValidateTokens\x12 .auth.BatchValidateTokensRequest\x1a!.auth.BatchValidateTokensResponseBEZCgithub.com/youknow2509/cio_verify_face/server/service_device/proto/pbb\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_auth_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),          // 0: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),         // 1: auth.ValidateTokenResponse
	(*GetUserInfoRequest)(nil),            // 2: auth.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),           // 3: auth.GetUserInfoResponse
	(*CheckUserPermissionRequest)(nil),    // 4: auth.CheckUserPermissionRequest
	(*CheckUserPermissionResponse)(nil),   // 5: auth.CheckUserPermissionResponse
	(*CheckDeviceInCompanyRequest)(nil),   // 6: auth.CheckDeviceInCompanyRequest
	(*CheckDeviceInCompanyResponse)(nil),  // 7: auth.CheckDeviceInCompanyResponse
	(*ValidateDeviceSessionRequest)(nil),  // 8: auth.ValidateDeviceSessionRequest
	(*ValidateDeviceSessionResponse)(nil), // 9: auth.ValidateDeviceSessionResponse
	(*GetUserCompanyRequest)(nil),         // 10: auth.GetUserCompanyRequest
	(*GetUserCompanyResponse)(nil),        // 11: auth.GetUserCompanyResponse
	(*TokenValidation)(nil),               // 12: auth.TokenValidation
	(*BatchValidateTokensRequest)(nil),    // 13: auth.BatchValidateTokensRequest
	(*TokenValidationResult)(nil),         // 14: auth.TokenValidationResult
	(*BatchValidateTokensResponse)(nil),   // 15: auth.BatchValidateTokensResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	12, // 0: auth.BatchValidateTokensRequest.tokens:type_name -> auth.TokenValidation
	14, // 1: auth.BatchValidateTokensResponse.results:type_name -> auth.TokenValidationResult
	0,  // 2: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	2,  // 3: auth.AuthService.GetUserInfo:input_type -> auth.GetUserInfoRequest
	4,  // 4: auth.AuthService.CheckUserPermission:input_type -> auth.CheckUserPermissionRequest
	6,  // 5: auth.AuthService.CheckDeviceInCompany:input_type -> auth.CheckDeviceInCompanyRequest
	8,  // 6: auth.AuthService.ValidateDeviceSession:input_type -> auth.ValidateDeviceSessionRequest
	10, // 7: auth.AuthService.GetUserCompany:input_type -> auth.GetUserCompanyRequest
	13, // 8: auth.AuthService.BatchValidateTokens:input_type -> auth.BatchValidateTokensRequest
	1,  // 9: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	3,  // 10: auth.AuthService.GetUserInfo:output_type -> auth.GetUserInfoResponse
	5,  // 11: auth.AuthService.CheckUserPermission:output_type -> auth.CheckUserPermissionResponse
	7,  // 12: auth.AuthService.CheckDeviceInCompany:output_type -> auth.CheckDeviceInCompanyResponse
	9,  // 13: auth.AuthService.ValidateDeviceSession:output_type -> auth.ValidateDeviceSessionResponse
	11, // 14: auth.AuthService.GetUserCompany:output_type -> auth.GetUserCompanyResponse
	15, // 15: auth.AuthService.BatchValidateTokens:output_type -> auth.BatchValidateTokensResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	file_proto_auth_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_auth_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_auth_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
