// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/face_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaceVerificationService_EnrollFace_FullMethodName          = "/face_verification.FaceVerificationService/EnrollFace"
	FaceVerificationService_VerifyFace_FullMethodName          = "/face_verification.FaceVerificationService/VerifyFace"
	FaceVerificationService_UpdateProfile_FullMethodName       = "/face_verification.FaceVerificationService/UpdateProfile"
	FaceVerificationService_DeleteProfile_FullMethodName       = "/face_verification.FaceVerificationService/DeleteProfile"
	FaceVerificationService_GetUserProfiles_FullMethodName     = "/face_verification.FaceVerificationService/GetUserProfiles"
	FaceVerificationService_CleanupProfiles_FullMethodName     = "/face_verification.FaceVerificationService/CleanupProfiles"
	FaceVerificationService_BatchEnrollFace_FullMethodName     = "/face_verification.FaceVerificationService/BatchEnrollFace"
	FaceVerificationService_BatchVerifyFace_FullMethodName     = "/face_verification.FaceVerificationService/BatchVerifyFace"
	FaceVerificationService_BatchDeleteProfile_FullMethodName  = "/face_verification.FaceVerificationService/BatchDeleteProfile"
	FaceVerificationService_BatchUpdateProfile_FullMethodName  = "/face_verification.FaceVerificationService/BatchUpdateProfile"
	FaceVerificationService_StreamEnrollFace_FullMethodName    = "/face_verification.FaceVerificationService/StreamEnrollFace"
	FaceVerificationService_StreamUpdateProfile_FullMethodName = "/face_verification.FaceVerificationService/StreamUpdateProfile"
)

// FaceVerificationServiceClient is the client API for FaceVerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceVerificationServiceClient interface {
	EnrollFace(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	VerifyFace(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	GetUserProfiles(ctx context.Context, in *GetUserProfilesRequest, opts ...grpc.CallOption) (*GetUserProfilesResponse, error)
	CleanupProfiles(ctx context.Context, in *CleanupProfilesRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Batch methods for server-to-server communication
	BatchEnrollFace(ctx context.Context, in *BatchEnrollRequest, opts ...grpc.CallOption) (*BatchEnrollResponse, error)
	BatchVerifyFace(ctx context.Context, in *BatchVerifyRequest, opts ...grpc.CallOption) (*BatchVerifyResponse, error)
	BatchDeleteProfile(ctx context.Context, in *BatchDeleteProfileRequest, opts ...grpc.CallOption) (*BatchDeleteProfileResponse, error)
	BatchUpdateProfile(ctx context.Context, in *BatchUpdateProfileRequest, opts ...grpc.CallOption) (*BatchUpdateProfileResponse, error)
	// Streaming methods for file uploads
	StreamEnrollFace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamEnrollRequest, EnrollResponse], error)
	StreamUpdateProfile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamUpdateProfileRequest, StatusResponse], error)
}

type faceVerificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceVerificationServiceClient(cc grpc.ClientConnInterface) FaceVerificationServiceClient {
	return &faceVerificationServiceClient{cc}
}

func (c *faceVerificationServiceClient) EnrollFace(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_EnrollFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) VerifyFace(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_VerifyFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) GetUserProfiles(ctx context.Context, in *GetUserProfilesRequest, opts ...grpc.CallOption) (*GetUserProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfilesResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_GetUserProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) CleanupProfiles(ctx context.Context, in *CleanupProfilesRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_CleanupProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) BatchEnrollFace(ctx context.Context, in *BatchEnrollRequest, opts ...grpc.CallOption) (*BatchEnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEnrollResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_BatchEnrollFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) BatchVerifyFace(ctx context.Context, in *BatchVerifyRequest, opts ...grpc.CallOption) (*BatchVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchVerifyResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_BatchVerifyFace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) BatchDeleteProfile(ctx context.Context, in *BatchDeleteProfileRequest, opts ...grpc.CallOption) (*BatchDeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteProfileResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_BatchDeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) BatchUpdateProfile(ctx context.Context, in *BatchUpdateProfileRequest, opts ...grpc.CallOption) (*BatchUpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateProfileResponse)
	err := c.cc.Invoke(ctx, FaceVerificationService_BatchUpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceVerificationServiceClient) StreamEnrollFace(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamEnrollRequest, EnrollResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaceVerificationService_ServiceDesc.Streams[0], FaceVerificationService_StreamEnrollFace_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEnrollRequest, EnrollResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceVerificationService_StreamEnrollFaceClient = grpc.ClientStreamingClient[StreamEnrollRequest, EnrollResponse]

func (c *faceVerificationServiceClient) StreamUpdateProfile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[StreamUpdateProfileRequest, StatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaceVerificationService_ServiceDesc.Streams[1], FaceVerificationService_StreamUpdateProfile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamUpdateProfileRequest, StatusResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceVerificationService_StreamUpdateProfileClient = grpc.ClientStreamingClient[StreamUpdateProfileRequest, StatusResponse]

// FaceVerificationServiceServer is the server API for FaceVerificationService service.
// All implementations must embed UnimplementedFaceVerificationServiceServer
// for forward compatibility.
type FaceVerificationServiceServer interface {
	EnrollFace(context.Context, *EnrollRequest) (*EnrollResponse, error)
	VerifyFace(context.Context, *VerifyRequest) (*VerifyResponse, error)
	UpdateProfile(context.Context, *UpdateProfileRequest) (*StatusResponse, error)
	DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error)
	GetUserProfiles(context.Context, *GetUserProfilesRequest) (*GetUserProfilesResponse, error)
	CleanupProfiles(context.Context, *CleanupProfilesRequest) (*StatusResponse, error)
	// Batch methods for server-to-server communication
	BatchEnrollFace(context.Context, *BatchEnrollRequest) (*BatchEnrollResponse, error)
	BatchVerifyFace(context.Context, *BatchVerifyRequest) (*BatchVerifyResponse, error)
	BatchDeleteProfile(context.Context, *BatchDeleteProfileRequest) (*BatchDeleteProfileResponse, error)
	BatchUpdateProfile(context.Context, *BatchUpdateProfileRequest) (*BatchUpdateProfileResponse, error)
	// Streaming methods for file uploads
	StreamEnrollFace(grpc.ClientStreamingServer[StreamEnrollRequest, EnrollResponse]) error
	StreamUpdateProfile(grpc.ClientStreamingServer[StreamUpdateProfileRequest, StatusResponse]) error
	mustEmbedUnimplementedFaceVerificationServiceServer()
}

// UnimplementedFaceVerificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaceVerificationServiceServer struct{}

func (UnimplementedFaceVerificationServiceServer) EnrollFace(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollFace not implemented")
}
func (UnimplementedFaceVerificationServiceServer) VerifyFace(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyFace not implemented")
}
func (UnimplementedFaceVerificationServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedFaceVerificationServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedFaceVerificationServiceServer) GetUserProfiles(context.Context, *GetUserProfilesRequest) (*GetUserProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserProfiles not implemented")
}
func (UnimplementedFaceVerificationServiceServer) CleanupProfiles(context.Context, *CleanupProfilesRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupProfiles not implemented")
}
func (UnimplementedFaceVerificationServiceServer) BatchEnrollFace(context.Context, *BatchEnrollRequest) (*BatchEnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchEnrollFace not implemented")
}
func (UnimplementedFaceVerificationServiceServer) BatchVerifyFace(context.Context, *BatchVerifyRequest) (*BatchVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchVerifyFace not implemented")
}
func (UnimplementedFaceVerificationServiceServer) BatchDeleteProfile(context.Context, *BatchDeleteProfileRequest) (*BatchDeleteProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteProfile not implemented")
}
func (UnimplementedFaceVerificationServiceServer) BatchUpdateProfile(context.Context, *BatchUpdateProfileRequest) (*BatchUpdateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdateProfile not implemented")
}
func (UnimplementedFaceVerificationServiceServer) StreamEnrollFace(grpc.ClientStreamingServer[StreamEnrollRequest, EnrollResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEnrollFace not implemented")
}
func (UnimplementedFaceVerificationServiceServer) StreamUpdateProfile(grpc.ClientStreamingServer[StreamUpdateProfileRequest, StatusResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamUpdateProfile not implemented")
}
func (UnimplementedFaceVerificationServiceServer) mustEmbedUnimplementedFaceVerificationServiceServer() {
}
func (UnimplementedFaceVerificationServiceServer) testEmbeddedByValue() {}

// UnsafeFaceVerificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceVerificationServiceServer will
// result in compilation errors.
type UnsafeFaceVerificationServiceServer interface {
	mustEmbedUnimplementedFaceVerificationServiceServer()
}

func RegisterFaceVerificationServiceServer(s grpc.ServiceRegistrar, srv FaceVerificationServiceServer) {
	// If the following call panics, it indicates UnimplementedFaceVerificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaceVerificationService_ServiceDesc, srv)
}

func _FaceVerificationService_EnrollFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).EnrollFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_EnrollFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).EnrollFace(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_VerifyFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).VerifyFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_VerifyFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).VerifyFace(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_GetUserProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).GetUserProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_GetUserProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).GetUserProfiles(ctx, req.(*GetUserProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_CleanupProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).CleanupProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_CleanupProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).CleanupProfiles(ctx, req.(*CleanupProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_BatchEnrollFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).BatchEnrollFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_BatchEnrollFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).BatchEnrollFace(ctx, req.(*BatchEnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_BatchVerifyFace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).BatchVerifyFace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_BatchVerifyFace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).BatchVerifyFace(ctx, req.(*BatchVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_BatchDeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).BatchDeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_BatchDeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).BatchDeleteProfile(ctx, req.(*BatchDeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_BatchUpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceVerificationServiceServer).BatchUpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceVerificationService_BatchUpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceVerificationServiceServer).BatchUpdateProfile(ctx, req.(*BatchUpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaceVerificationService_StreamEnrollFace_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FaceVerificationServiceServer).StreamEnrollFace(&grpc.GenericServerStream[StreamEnrollRequest, EnrollResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceVerificationService_StreamEnrollFaceServer = grpc.ClientStreamingServer[StreamEnrollRequest, EnrollResponse]

func _FaceVerificationService_StreamUpdateProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FaceVerificationServiceServer).StreamUpdateProfile(&grpc.GenericServerStream[StreamUpdateProfileRequest, StatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaceVerificationService_StreamUpdateProfileServer = grpc.ClientStreamingServer[StreamUpdateProfileRequest, StatusResponse]

// FaceVerificationService_ServiceDesc is the grpc.ServiceDesc for FaceVerificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceVerificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "face_verification.FaceVerificationService",
	HandlerType: (*FaceVerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollFace",
			Handler:    _FaceVerificationService_EnrollFace_Handler,
		},
		{
			MethodName: "VerifyFace",
			Handler:    _FaceVerificationService_VerifyFace_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _FaceVerificationService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _FaceVerificationService_DeleteProfile_Handler,
		},
		{
			MethodName: "GetUserProfiles",
			Handler:    _FaceVerificationService_GetUserProfiles_Handler,
		},
		{
			MethodName: "CleanupProfiles",
			Handler:    _FaceVerificationService_CleanupProfiles_Handler,
		},
		{
			MethodName: "BatchEnrollFace",
			Handler:    _FaceVerificationService_BatchEnrollFace_Handler,
		},
		{
			MethodName: "BatchVerifyFace",
			Handler:    _FaceVerificationService_BatchVerifyFace_Handler,
		},
		{
			MethodName: "BatchDeleteProfile",
			Handler:    _FaceVerificationService_BatchDeleteProfile_Handler,
		},
		{
			MethodName: "BatchUpdateProfile",
			Handler:    _FaceVerificationService_BatchUpdateProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEnrollFace",
			Handler:       _FaceVerificationService_StreamEnrollFace_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamUpdateProfile",
			Handler:       _FaceVerificationService_StreamUpdateProfile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/face_service.proto",
}
